#!/usr/bin/env node
// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.

// Agent Bridge: connects the Chrome extension to the AI coding agent.
// This HTTP server acts as middleware between a browser extension (which collects
// user annotations/feedback on a live web page) and an AI CLI tool (claude-code or
// kiro-cli) that applies code changes based on those annotations.
//
// Flow: Browser Extension → HTTP POST → Agent Bridge → AI CLI → Code Changes → Verification
//
// CLI-agnostic — works with claude-code, kiro-cli, or any CLI that accepts a prompt.
// Args: --port PORT --feedback PATH --app-dir PATH --cli CMD

const http = require('http');
const fs = require('fs');
const path = require('path');
let marked;
try {
  ({ marked } = require('marked'));
  // Render Markdown reports as HTML via `marked` (GFM: tables, lists, etc.).
  // gfm + breaks match how the verification report.md is authored.
  marked.setOptions({ gfm: true, breaks: true });
} catch (e) {
  process.stderr.write(
    "[agent-bridge] Missing dependency 'marked'. Install the agent-bridge deps first:\n" +
    "  npm install --prefix tools/agent-bridge\n"
  );
  process.exit(1);
}

// Parse command-line arguments for server configuration
const args = process.argv.slice(2);
let port, feedbackPath, appDir, cliCmd;

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--port' && args[i + 1]) port = parseInt(args[++i]);       // HTTP server port
  if (args[i] === '--feedback' && args[i + 1]) feedbackPath = args[++i];     // JSON file to persist annotations
  if (args[i] === '--app-dir' && args[i + 1]) appDir = args[++i];           // Workspace root for the target app
  if (args[i] === '--cli' && args[i + 1]) cliCmd = args[++i];               // AI CLI binary (claude or kiro-cli)
}

if (!port || !feedbackPath) {
  process.stderr.write(`Usage: node agent-bridge.js --port 9999 --feedback .tmp/feedback.json --app-dir /path/to/app [--cli claude]

Options:
  --port              Port for the agent bridge (required)
  --feedback          Path to store annotation feedback JSON (required)
  --app-dir           Your app's workspace root
  --cli               AI CLI command (default: kiro-cli, pass "claude" for Claude Code)
`);
  process.exit(1);
}

// Auto-detect which AI CLI is available on the system.
// Priority: user-specified --cli flag > kiro-cli on PATH > kiro-cli in ~/.local/bin > claude
function detectCli() {
  if (cliCmd) {
    // If user passed 'kiro-cli' or 'kiro', resolve to full path if needed
    if (cliCmd.includes('kiro') && !cliCmd.startsWith('/')) {
      const kiroPaths = [(process.env.HOME || '') + '/.local/bin/kiro-cli'];
      for (const p of kiroPaths) { if (fs.existsSync(p)) return p; }
    }
    return cliCmd;
  }
  const { execSync } = require('child_process');
  // Prefer kiro-cli
  try { execSync('which kiro-cli', { stdio: 'ignore' }); return 'kiro-cli'; } catch (_) {}
  // Check common kiro-cli install paths
  const kiroPath = (process.env.HOME || '') + '/.local/bin/kiro-cli';
  if (fs.existsSync(kiroPath)) return kiroPath;
  // Fall back to claude
  try { execSync('which claude', { stdio: 'ignore' }); return 'claude'; } catch (_) {}
  process.stderr.write('[agent-bridge] WARNING: No AI CLI detected. Install kiro-cli or claude-code.\n');
  return 'kiro-cli';
}

// Build the shell command to invoke the AI CLI for code-editing tasks (apply annotations).
// Each CLI has different flags for non-interactive mode and prompt input.
function buildCliCommand(cli, promptFile, effort) {
  var file = path.resolve(promptFile);
  if (cli.includes('claude')) {
    // Pipe file content to avoid shell quoting issues with JSON in the prompt
    return `cat '${file}' | ${cli} --dangerously-skip-permissions -p`;
  }
  if (cli.includes('kiro')) {
    return `${cli} chat -a --resume --no-interactive --effort ${effort || 'max'} "$(cat '${file}')" < /dev/null`;
  }
  return `${cli} "$(cat '${file}')" < /dev/null`;
}

// Build the shell command for lightweight chat queries (no file editing, lower effort).
// Used by the /api/chat endpoint for quick CSS design questions.
function buildChatCommand(cli, promptFile) {
  var file = path.resolve(promptFile);
  if (cli.includes('claude')) {
    return `cat '${file}' | ${cli} -p`;
  }
  if (cli.includes('kiro')) {
    return `${cli} chat --no-interactive --effort low "$(cat '${file}')" < /dev/null`;
  }
  return `${cli} "$(cat '${file}')" < /dev/null`;
}

// Generate a filesystem-safe timestamp string (e.g., "2026-06-25_14-30-05")
function generateTimestamp() {
  const now = new Date();
  return now.getFullYear() + '-' +
    String(now.getMonth() + 1).padStart(2, '0') + '-' +
    String(now.getDate()).padStart(2, '0') + '_' +
    String(now.getHours()).padStart(2, '0') + '-' +
    String(now.getMinutes()).padStart(2, '0') + '-' +
    String(now.getSeconds()).padStart(2, '0');
}

// Generate a short unique session ID for tracking apply operations
function generateSessionId() {
  return Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8);
}

const CLI = detectCli();
// Ensure common binary locations are on PATH when spawning child processes
const EXEC_ENV = Object.assign({}, process.env, { PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin:' + (process.env.HOME || '') + '/.local/bin' });

process.stderr.write(`[agent-bridge] Using CLI: ${CLI}\n`);

// Structured logger — writes timestamped messages to stderr with a category tag
function log(tag, msg) {
  const ts = new Date().toISOString().replace('T', ' ').slice(0, 19);
  process.stderr.write(`[${ts}] [${tag}] ${msg}\n`);
}

// Convert a Markdown verification report to HTML via the `marked` library.
// Replaces the previous hand-rolled regex converter, which did not handle
// tables and leaked raw "|---|" rows into the rendered report.
function renderMarkdown(md) {
  return marked.parse(md);
}

// ─── HTTP Server ───────────────────────────────────────────────────────────────
// API Endpoints:
//   POST   /api/feedback       — Store a single annotation from the browser extension
//   DELETE  /api/feedback       — Clear all stored annotations
//   POST   /api/chat           — Ask the AI a quick CSS design question
//   GET    /api/apply/status   — Poll the status of an in-progress apply operation
//   POST   /api/apply          — Send annotations to the AI CLI to edit source code
//   GET    /api/report/latest  — Get path to the most recent verification report
//   GET    /api/report/view    — Serve the latest report as rendered HTML
// ───────────────────────────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  // Don't log status polls — they fire every 3s and spam the terminal
  if (req.url !== '/api/apply/status') {
    log('req', `${req.method} ${req.url}`);
  }

  // Handle CORS preflight requests so the browser extension can call us cross-origin
  if (req.url && req.url.startsWith('/api/') && req.method === 'OPTIONS') {
    log('cors', `Preflight for ${req.url}`);
    res.writeHead(204, { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'POST,DELETE,GET', 'Access-Control-Allow-Headers': 'Content-Type' });
    res.end();
    return;
  }

  // ─── /api/feedback ── Store or clear individual annotations ─────────────────
  if (req.url === '/api/feedback') {
    if (req.method === 'POST') {
      let body = '';
      req.on('data', chunk => body += chunk);
      req.on('end', () => {
        try {
          const entry = JSON.parse(body);
          log('feedback', `Received annotation: "${entry.feedback || '(no text)'}" on ${entry.selector || entry.tag || 'unknown'}`);
          let existing = [];
          if (fs.existsSync(feedbackPath)) {
            existing = JSON.parse(fs.readFileSync(feedbackPath, 'utf-8'));
          }
          existing.push(entry);
          fs.mkdirSync(path.dirname(feedbackPath), { recursive: true });
          fs.writeFileSync(feedbackPath, JSON.stringify(existing, null, 2));
          log('feedback', `Saved to ${feedbackPath} (${existing.length} total annotations)`);
          res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
          res.end('{"ok":true}');
        } catch (err) {
          log('feedback', `ERROR: ${err.message}`);
          res.writeHead(400, { 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ error: err.message }));
        }
      });
    } else if (req.method === 'DELETE') {
      log('feedback', 'Clearing all annotations');
      fs.mkdirSync(path.dirname(feedbackPath), { recursive: true });
      fs.writeFileSync(feedbackPath, '[]');
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end('{"ok":true}');
    } else {
      res.writeHead(405);
      res.end();
    }
    return;
  }

  // ─── /api/chat ── Quick AI Q&A for CSS design help ──────────────────────────
  // The extension sends a design question (optionally with a screenshot).
  // Uses low-effort CLI mode for fast responses without file editing.
  if (req.url === '/api/chat') {
    if (req.method === 'POST') {
      let body = '';
      req.on('data', chunk => body += chunk);
      req.on('end', () => {
        try {
          const payload = JSON.parse(body);
          log('chat', `Question: "${(payload.question || '').slice(0, 100)}${(payload.question || '').length > 100 ? '...' : ''}"`);
          if (payload.imageBase64) log('chat', 'Includes screenshot attachment');
          const chatDir = path.join(path.dirname(feedbackPath), 'chat');
          fs.mkdirSync(chatDir, { recursive: true });
          const id = Date.now().toString();

          // Save screenshot to disk if provided (for potential future reference)
          if (payload.imageBase64) {
            const screenshotPath = path.join(chatDir, id + '.jpg');
            fs.writeFileSync(screenshotPath, Buffer.from(payload.imageBase64, 'base64'));
          }

          // System prompt instructs the AI to return CSS patches in a structured format
          const questionText = payload.question || '';
          const prompt = 'CSS design assistant. For CSS changes return a patches code block with JSON array of {selector, property (camelCase), value, label}. Be concise.\n\n' + questionText;

          const promptFile = path.join(chatDir, id + '.prompt.txt');
          fs.writeFileSync(promptFile, prompt);
          // Write prompt to a temp file, invoke the CLI, then clean up
          const { exec } = require('child_process');
          const cmd = buildChatCommand(CLI, promptFile);
          log('chat', `Invoking CLI: ${cmd.slice(0, 120)}...`);
          exec(cmd, { timeout: 90000, env: EXEC_ENV, cwd: appDir || process.cwd() }, function (err, stdout) {
            try { fs.unlinkSync(promptFile); } catch (_) {}
            if (err) {
              log('chat', `CLI error: ${err.message}`);
              res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
              res.end(JSON.stringify({ answer: 'CLI error: ' + (err.message || 'timeout') }));
              return;
            }
            // Strip ANSI color codes and leading prompt markers from CLI output
            const clean = stdout.replace(/\x1B\[[0-9;]*m/g, '').replace(/^> /, '').trim();
            log('chat', `Response received (${clean.length} chars)`);
            res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
            res.end(JSON.stringify({ answer: clean }));
          });
        } catch (err) {
          log('chat', `ERROR: ${err.message}`);
          res.writeHead(400, { 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ error: err.message }));
        }
      });
    } else {
      res.writeHead(405);
      res.end();
    }
    return;
  }

  // ─── /api/apply/status ── Poll for apply operation progress ─────────────────
  // Returns: { status: 'idle' | 'running' | 'verifying' | 'done' | 'error', ... }
  if (req.url === '/api/apply/status') {
    const statusFile = path.join(path.dirname(feedbackPath), 'apply-status.json');
    if (fs.existsSync(statusFile)) {
      const status = fs.readFileSync(statusFile, 'utf-8');
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(status);
    } else {
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(JSON.stringify({ status: 'idle' }));
    }
    return;
  }

  // ─── /api/report/latest ── Return metadata about the most recent verification report
  if (req.url === '/api/report/latest') {
    log('report', 'Fetching latest report');
    const execCwd = appDir || process.cwd();
    const reportsDir = path.join(execCwd, '.ui-verification', 'reports');
    var report = null;
    var reportPath = null;
    var reportTime = null;
    try {
      if (fs.existsSync(reportsDir)) {
        const dirs = fs.readdirSync(reportsDir).filter(d => fs.statSync(path.join(reportsDir, d)).isDirectory()).sort().reverse();
        for (const dir of dirs) {
          const rp = path.join(reportsDir, dir, 'report.md');
          if (fs.existsSync(rp)) {
            report = '.ui-verification/reports/' + dir + '/report.md';
            reportPath = rp;
            reportTime = fs.statSync(rp).mtimeMs;
            break;
          }
        }
      }
    } catch (_) {}
    log('report', report ? `Found: ${report}` : 'No report found');
    res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
    res.end(JSON.stringify({ report: report, reportPath: reportPath, timestamp: reportTime }));
    return;
  }

  // ─── /api/report/screenshots/<file> ── Serve a screenshot referenced by the report.
  // report.md uses relative paths like "screenshots/full-page.png", which the browser
  // resolves against /api/report/view → /api/report/screenshots/<file>.
  const shotMatch = req.url.match(/^\/api\/report\/screenshots\/([A-Za-z0-9._-]+)$/);
  if (shotMatch) {
    const execCwd = appDir || process.cwd();
    const reportsDir = path.join(execCwd, '.ui-verification', 'reports');
    try {
      const dirs = fs.readdirSync(reportsDir).filter(d => fs.statSync(path.join(reportsDir, d)).isDirectory()).sort().reverse();
      for (const dir of dirs) {
        const imgPath = path.join(reportsDir, dir, 'screenshots', shotMatch[1]);
        if (fs.existsSync(imgPath)) {
          const ext = path.extname(imgPath).toLowerCase();
          const type = ext === '.jpg' || ext === '.jpeg' ? 'image/jpeg' : 'image/png';
          res.writeHead(200, { 'Content-Type': type, 'Access-Control-Allow-Origin': '*' });
          res.end(fs.readFileSync(imgPath));
          return;
        }
      }
    } catch (_) {}
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Screenshot not found');
    return;
  }

  // ─── /api/report/view ── Serve the report as rendered HTML (simple markdown→HTML)
  if (req.url === '/api/report/view') {
    log('report', 'Serving report HTML view');
    const execCwd = appDir || process.cwd();
    const reportsDir = path.join(execCwd, '.ui-verification', 'reports');
    try {
      const dirs = fs.readdirSync(reportsDir).filter(d => fs.statSync(path.join(reportsDir, d)).isDirectory()).sort().reverse();
      for (const dir of dirs) {
        const rp = path.join(reportsDir, dir, 'report.md');
        if (fs.existsSync(rp)) {
          const content = fs.readFileSync(rp, 'utf-8');
          const html = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>UI Verification Report</title>' +
            '<style>body{font-family:-apple-system,sans-serif;max-width:900px;margin:40px auto;padding:0 20px;color:#1a1a2e;line-height:1.6}' +
            'table{border-collapse:collapse;width:100%;margin:1em 0}th,td{border:1px solid #e9ecef;padding:8px 12px;text-align:left}' +
            'th{background:#f8f9fa}code{background:#f0f0f0;padding:2px 5px;border-radius:3px;font-size:0.9em}' +
            'h1{border-bottom:2px solid #6c63ff;padding-bottom:8px}h2{margin-top:2em}details{margin:1em 0}' +
            'hr{border:0;border-top:1px solid #e9ecef;margin:2em 0}ul{margin:1em 0;padding-left:1.5em}' +
            'img{max-width:100%;height:auto;border:1px solid #e9ecef;border-radius:4px}' +
            'summary{cursor:pointer;font-weight:600}</style></head><body>' +
            renderMarkdown(content) +
            '</body></html>';
          res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Access-Control-Allow-Origin': '*' });
          res.end(html);
          return;
        }
      }
    } catch (_) {}
    res.writeHead(404, { 'Content-Type': 'text/html' });
    res.end('<html><body><h1>No report found</h1><p>Run verification first.</p></body></html>');
    return;
  }


  // ─── /api/apply ── Main endpoint: send annotations to the AI CLI for code editing ──
  // This is the core workflow:
  //   1. Receive annotations from the browser extension
  //   2. Build a prompt instructing the AI to edit CSS/source files
  //   3. Invoke the AI CLI asynchronously (responds immediately with sessionId)
  //   4. After CLI finishes, wait for the dev server to be ready
  //   5. Run visual verification via Nova Act (Python script)
  //   6. Update status file so the extension can poll for completion
  if (req.url === '/api/apply') {
    if (req.method === 'POST') {
      let body = '';
      req.on('data', chunk => body += chunk);
      req.on('end', () => {
        try {
          const payload = JSON.parse(body);
          const tmpDir = path.dirname(feedbackPath);
          fs.mkdirSync(tmpDir, { recursive: true });

          const annotations = payload.annotations || [];
          fs.writeFileSync(feedbackPath, JSON.stringify(annotations, null, 2));

          const sessionId = generateSessionId();
          const ts = generateTimestamp();

          log('apply', `Received ${annotations.length} annotations (session: ${sessionId})`);
          annotations.forEach(function (a, i) {
            log('apply', `  #${i + 1}: "${a.feedback || '(empty)'}" → ${a.selector || '(no selector)'}`);
          });

          // Format annotations into a human-readable summary for the AI prompt
          const feedbackSummary = annotations.map(function (a, i) {
            return (i + 1) + '. [element]    "' + a.feedback + '"\n             selector: ' + a.selector;
          }).join('\n\n');

          const annotationFileName = ts + '_' + sessionId + '.json';
          const annotationContent = JSON.stringify({ sessionId: sessionId, appliedAt: new Date().toISOString(), url: payload.url, annotations: annotations });

          // Construct the prompt that tells the AI CLI what to change in the source files
          const prompt = 'Edit source code files in this workspace to implement these design changes. Do not ask clarifying questions — use your best judgement and apply the changes directly. For each annotation, search the codebase for the CSS selector or class names to find the source file and edit it. If visual/design.md exists, update it too.\n\nAfter all code changes are applied, create the file annotations/' + annotationFileName + ' with this exact content:\n' + annotationContent + '\n\n# Notes\n\n' + feedbackSummary;

          // Write status file so the extension can poll via /api/apply/status
          const statusFile = path.join(tmpDir, 'apply-status.json');
          fs.writeFileSync(statusFile, JSON.stringify({ status: 'running', sessionId: sessionId, timestamp: Date.now() }));

          // Respond immediately — the AI CLI runs asynchronously in the background
          res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ ok: true, sessionId: sessionId, message: CLI + ' is applying changes...' }));

          // Write prompt to a temp file and invoke the CLI
          const { exec } = require('child_process');
          const promptFile = path.join(tmpDir, 'apply-prompt.txt');
          fs.writeFileSync(promptFile, prompt);

          const execCwd = appDir || process.cwd();
          const cmd = buildCliCommand(CLI, promptFile, 'max');
          log('apply', `Invoking CLI in ${execCwd}`);
          log('apply', `Command: ${cmd.slice(0, 200)}${cmd.length > 200 ? '...' : ''}`);

          // 5-minute timeout; kiro-cli "No session" error triggers a retry without --resume
          exec(cmd, { timeout: 300000, cwd: execCwd, env: EXEC_ENV }, function (err, stdout, stderr) {
            if (err && CLI.includes('kiro') && (stderr || '').includes('No session')) {
              log('apply', 'Got "No session" error, retrying without --resume...');
              const retryCmd = `${CLI} chat -a --no-interactive --effort max "$(cat '${path.resolve(promptFile)}')" < /dev/null`;
              exec(retryCmd, { timeout: 300000, cwd: execCwd, env: EXEC_ENV }, onApplyDone);
              return;
            }
            onApplyDone(err, stdout, stderr);
          });

          // Callback after CLI finishes (or after retry)
          function onApplyDone(err, stdout, stderr) {
            try { fs.unlinkSync(promptFile); } catch (_) {}

            // Save CLI logs for debugging
            try {
              const logsDir = path.join(execCwd, 'logs', 'cli');
              fs.mkdirSync(logsDir, { recursive: true });
              const logTs = generateTimestamp();
              const logContent = '--- CLI APPLY LOG ---\n' +
                'CLI: ' + CLI + '\n' +
                'Session: ' + sessionId + '\n' +
                'Timestamp: ' + new Date().toISOString() + '\n' +
                'Status: ' + (err ? 'FAILED' : 'SUCCESS') + '\n' +
                (err ? 'Error: ' + err.message + '\n' : '') +
                '\n--- STDOUT ---\n' + (stdout || '(empty)') +
                '\n--- STDERR ---\n' + (stderr || '(empty)') + '\n';
              const logFile = path.join(logsDir, logTs + '_' + sessionId + '.log');
              fs.writeFileSync(logFile, logContent);
              log('apply', `CLI log saved: ${logFile}`);
            } catch (e) {
              log('apply', `Failed to save CLI log: ${e.message}`);
            }

            if (err) {
              log('apply', `CLI FAILED: ${(stderr || err.message).slice(0, 300)}`);
              fs.writeFileSync(statusFile, JSON.stringify({ status: 'error', sessionId: sessionId, error: err.message, timestamp: Date.now() }));
              return;
            }

            // After successful code edit, poll the dev server until it's responsive
            // (the code changes may have triggered a rebuild/hot-reload)
            log('apply', 'CLI finished successfully. Checking dev server...');
            const appUrl = payload.url || 'http://localhost:5173';
            var attempts = 0;
            function checkServer() {
              attempts++;
              http.get(appUrl, function (r) {
                r.resume();
                if (r.statusCode >= 200 && r.statusCode < 500) {
                  log('apply', `Dev server responding (status ${r.statusCode}, attempt ${attempts})`);
                  runVerification();
                } else if (attempts < 20) {
                  setTimeout(checkServer, 2000);
                } else {
                  log('apply', `Dev server returned ${r.statusCode} after ${attempts} attempts, running verification anyway`);
                  runVerification();
                }
              }).on('error', function (e) {
                if (attempts < 20) {
                  if (attempts === 1 || attempts % 5 === 0) log('apply', `Waiting for dev server (attempt ${attempts})... ${e.message}`);
                  setTimeout(checkServer, 2000);
                } else {
                  log('apply', `Dev server not responding after ${attempts} attempts: ${e.message}`);
                  fs.writeFileSync(statusFile, JSON.stringify({ status: 'error', sessionId: sessionId, error: 'Dev server not responding', timestamp: Date.now() }));
                }
              });
            }
            checkServer();

            // Once the dev server is ready, run visual verification using Nova Act
            // to confirm the AI's code changes actually match the requested design
            function runVerification() {
              log('apply', 'Running verification...');
              fs.writeFileSync(statusFile, JSON.stringify({ status: 'verifying', sessionId: sessionId, timestamp: Date.now() }));

              const verifyScript = path.join(__dirname, 'verify-with-nova-act.py');
              const verifyEnv = Object.assign({}, EXEC_ENV, { NOVA_ACT_API_KEY: process.env.NOVA_ACT_API_KEY || '4319cc3b-8831-4c0a-82a9-1df7794af3d5' });
              // Use venv python if available, otherwise system python3
              const venvPython = path.resolve(execCwd, '..', '.venv', 'bin', 'python3');
              const pythonBin = fs.existsSync(venvPython) ? venvPython : 'python3';
              const absAppDir = path.resolve(execCwd);
              const verifyCmd = `${pythonBin} "${verifyScript}" --app-dir "${absAppDir}" --url "${appUrl}"`;
              log('apply', `Verify command: ${verifyCmd}`);
              exec(verifyCmd, { timeout: 300000, cwd: absAppDir, env: verifyEnv }, function (err2, stdout2, stderr2) {
                if (err2) {
                  var errMsg = (stderr2 || err2.message || '').replace(/\x1B\[[0-9;]*m/g, '').trim().slice(-500);
                  log('apply', `Verification FAILED: ${errMsg}`);
                  fs.writeFileSync(statusFile, JSON.stringify({ status: 'error', sessionId: sessionId, error: 'Verification failed: ' + errMsg, timestamp: Date.now() }));
                  return;
                }
                var report = null;
                try {
                  const result = JSON.parse((stdout2 || '').trim());
                  report = result.report || null;
                } catch (_) {
                  try {
                    const reportsDir = path.join(execCwd, '.ui-verification', 'reports');
                    if (fs.existsSync(reportsDir)) {
                      const dirs = fs.readdirSync(reportsDir).filter(d => fs.statSync(path.join(reportsDir, d)).isDirectory()).sort().reverse();
                      for (const dir of dirs) {
                        const rp = path.join(reportsDir, dir, 'report.md');
                        if (fs.existsSync(rp)) { report = '.ui-verification/reports/' + dir + '/report.md'; break; }
                      }
                    }
                  } catch (_) {}
                }
                var reportAbsPath = report ? path.join(execCwd, report) : null;
                fs.writeFileSync(statusFile, JSON.stringify({ status: 'done', sessionId: sessionId, report: report, reportPath: reportAbsPath, timestamp: Date.now() }));
                log('apply', `✓ Verification complete. Report: ${report || 'none'}`);
              });
            }
          }
        } catch (err) {
          log('apply', `ERROR parsing request: ${err.message}`);
          res.writeHead(400, { 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ error: err.message }));
        }
      });
    } else {
      res.writeHead(405);
      res.end();
    }
    return;
  }

  // API-only mode — no proxy
  log('req', `404 — unknown route: ${req.method} ${req.url}`);
  res.writeHead(404, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
  res.end(JSON.stringify({ error: 'Not found' }));
});

// Start the server and signal readiness to the parent process via stdout
server.listen(port, () => {
  process.stderr.write(`[agent-bridge] Listening on http://localhost:${port}\n`);
  process.stderr.write(`[agent-bridge] App dir: ${appDir || process.cwd()}\n`);
  process.stdout.write(`READY\n`);
});
