#!/usr/bin/env python3
# Copyright 2026 Amazon Inc

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# WARNING: this file is auto-generated by scripts/generate_sync.py
# Source: src/nova_act/asyncio/nova_act.py
# DO NOT EDIT — changes will be overwritten. Modify the async source instead.
"""
verify-with-nova-act.py
Runs ui-verification using the nova-act Python SDK directly.
Mirrors the ui-verification skill: visual CSS checks + flow verification.
Usage: python verify-with-nova-act.py --app-dir /path/to/app --url http://localhost:5173
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from nova_act import NovaAct


def load_rules(app_dir):
    """Load visual rules from .ui-verification/specs/*.md"""
    specs_dir = Path(app_dir) / '.ui-verification' / 'specs'
    rules = []
    if not specs_dir.exists():
        return rules
    for f in specs_dir.glob('*.md'):
        category = f.stem
        for line in f.read_text().splitlines():
            m = re.match(r'^\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|\s*([^|]+)\|$', line)
            if m and 'Name' not in m.group(1) and '---' not in m.group(1):
                rules.append({
                    'name': m.group(1).strip(),
                    'selector': m.group(2).strip(),
                    'property': m.group(3).strip(),
                    'constraint': m.group(4).strip(),
                    'category': category,
                })
    return rules


def load_flows(app_dir):
    """Load .feature files from .ui-verification/flows/"""
    flows_dir = Path(app_dir) / '.ui-verification' / 'flows'
    flows = []
    if not flows_dir.exists():
        return flows
    for f in sorted(flows_dir.glob('*.feature')):
        content = f.read_text()
        # Parse metadata from header comments
        flow_type = 'state_completeness'
        feature_title = f.stem
        scenario_title = 'Verification scenario'
        for line in content.splitlines():
            if line.startswith('# type:'):
                flow_type = line.split(':', 1)[1].strip()
            elif line.startswith('Feature:'):
                feature_title = line.split(':', 1)[1].strip()
            elif line.strip().startswith('Scenario:'):
                scenario_title = line.strip().split(':', 1)[1].strip()
        flows.append({
            'name': f.stem,
            'content': content,
            'type': flow_type,
            'feature_title': feature_title,
            'scenario_title': scenario_title,
        })
    return flows


def build_check_script(rules):
    """Build JS to check all CSS rules in one shot"""
    rules_json = json.dumps([{'name': r['name'], 'selector': r['selector'], 'property': r['property'], 'constraint': r['constraint']} for r in rules])
    return "(function() {\n" \
        "    var rules = " + rules_json + ";\n" \
        "    return JSON.stringify(rules.map(function(rule) {\n" \
        "        var els = document.querySelectorAll(rule.selector);\n" \
        "        if (els.length === 0) return {name: rule.name, pass: false, actual: 'SELECTOR_NOT_FOUND', expected: rule.constraint};\n" \
        "        var val = window.getComputedStyle(els[0]).getPropertyValue(rule.property);\n" \
        "        var c = rule.constraint, pass = false;\n" \
        "        if (c.charAt(0) === '=') pass = val === c.slice(1);\n" \
        "        else if (c.charAt(0) === '~') { var expected = c.slice(1).replace(/[() ]/g,''); pass = val.replace(/[() ]/g,'').includes(expected); }\n" \
        "        else if (c.indexOf('contains:') === 0) pass = val.indexOf(c.slice(9)) !== -1;\n" \
        "        else if (c.indexOf('>=') === 0) pass = parseFloat(val) >= parseFloat(c.slice(2));\n" \
        "        else pass = val === c;\n" \
        "        return {name: rule.name, pass: pass, actual: val, expected: c};\n" \
        "    }));\n" \
        "})()"


def parse_steps(content):
    """Parse Gherkin .feature file into steps"""
    steps = []
    last_type = 'then'
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith('Given '):
            steps.append(('given', stripped[6:]))
            last_type = 'given'
        elif stripped.startswith('When '):
            steps.append(('when', stripped[5:]))
            last_type = 'when'
        elif stripped.startswith('Then '):
            steps.append(('then', stripped[5:]))
            last_type = 'then'
        elif stripped.startswith('And '):
            steps.append((last_type, stripped[4:]))
    return steps


def run_verification(app_url, app_dir, rules, flows):
    """Run visual + flow verification using NovaAct SDK"""
    print(f"[start] Verifying {app_url}...", file=sys.stderr)

    visual_results = []
    flow_results = []

    logs_dir = str(Path(app_dir) / 'logs' / 'nova_act')
    os.makedirs(logs_dir, exist_ok=True)

    with NovaAct(starting_page=app_url, headless=True, nova_act_api_key=os.environ.get('NOVA_ACT_API_KEY', ''), ignore_https_errors=True, logs_directory=logs_dir) as nova:
        # ── Visual checks: evaluate JS directly via Playwright (no LLM needed) ──
        if rules:
            print(f"[visual] Checking {len(rules)} CSS rules...", file=sys.stderr)
            script = build_check_script(rules)
            try:
                page = nova.page
                raw = page.evaluate(script)
                visual_results = json.loads(raw) if isinstance(raw, str) else raw
                print(f"[visual] Got {len(visual_results)} results", file=sys.stderr)
            except Exception as e:
                print(f"[visual] Evaluate failed: {e}", file=sys.stderr)
                visual_results = [{'name': r['name'], 'pass': False, 'actual': 'EVAL_ERROR', 'expected': r['constraint']} for r in rules]

            # Capture screenshot (separate try so it doesn't affect results)
            try:
                screenshots_dir = Path(app_dir) / '.ui-verification' / 'reports' / '_pending_screenshots'
                screenshots_dir.mkdir(parents=True, exist_ok=True)
                nova.page.screenshot(path=str(screenshots_dir / 'full-page.png'), full_page=True)
                print(f"[visual] Screenshot captured", file=sys.stderr)
            except Exception as e:
                print(f"[visual] Screenshot failed: {e}", file=sys.stderr)

        # ── Flow checks ──
        for flow in flows:
            print(f"[flow] Running {flow['name']}...", file=sys.stderr)
            steps = parse_steps(flow['content'])
            step_results = []
            flow_pass = True

            for stype, text in steps:
                if stype in ('given', 'when'):
                    try:
                        if 'scroll to the bottom' in text or 'scroll to' in text.lower():
                            nova.act("Scroll to the very bottom of the page", max_steps=10)
                            step_results.append({'step': text, 'pass': True, 'type': stype})
                        elif 'page finishes loading' in text or 'I am on' in text:
                            step_results.append({'step': text, 'pass': True, 'type': stype})
                        else:
                            nova.act(text, max_steps=10)
                            step_results.append({'step': text, 'pass': True, 'type': stype})
                    except Exception as e:
                        step_results.append({'step': text, 'pass': False, 'type': stype})
                        flow_pass = False
                else:
                    # Then/And — verify assertion
                    try:
                        nova.act(f"Verify: {text}. Return PASS if true, FAIL if not.", max_steps=10)
                        step_results.append({'step': text, 'pass': True, 'type': stype})
                    except Exception as e:
                        step_results.append({'step': text, 'pass': False, 'type': stype})
                        flow_pass = False

            flow_results.append({
                'name': flow['name'],
                'pass': flow_pass,
                'steps': step_results,
                'type': flow.get('type', 'state_completeness'),
                'feature_title': flow.get('feature_title', flow['name']),
                'scenario_title': flow.get('scenario_title', 'Verification scenario'),
            })

    return visual_results, flow_results


def write_report(app_dir, app_url, rules, visual_results, flow_results):
    """Write report matching ui-verification skill format"""
    ts = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')
    report_dir = Path(app_dir) / '.ui-verification' / 'reports' / ts
    (report_dir / 'screenshots').mkdir(parents=True, exist_ok=True)
    (report_dir / 'flow-reports').mkdir(parents=True, exist_ok=True)

    v_passed = sum(1 for r in visual_results if r.get('pass'))
    v_failed = len(visual_results) - v_passed
    total = len(visual_results)

    # Category counts
    cats = {}
    for rule in rules:
        res = next((r for r in visual_results if r['name'] == rule['name']), None)
        cat = rule['category']
        if cat not in cats:
            cats[cat] = {'total': 0, 'passed': 0, 'failed': 0}
        cats[cat]['total'] += 1
        if res and res.get('pass'):
            cats[cat]['passed'] += 1
        else:
            cats[cat]['failed'] += 1

    # Compute effective pass rate (excluding accessibility false negatives)
    acc_false_neg = cats.get('accessibility', {}).get('failed', 0)
    effective_total = total - acc_false_neg
    effective_passed = v_passed
    effective_rate = f"{effective_passed}/{effective_total} = {100*effective_passed/effective_total:.1f}%" if effective_total > 0 else "N/A"

    report = f"""# UI Verification Report — Some Podcast

**URL:** {app_url}  
**Date:** {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}  
**Mode:** Visual + Flow verification

---

## Summary

| Category | Rules | Passed | Failed | Pass Rate |
|----------|-------|--------|--------|-----------|
"""
    for cat, c in cats.items():
        label = cat.replace('-', ' ').title()
        rate = f"{100*c['passed']/c['total']:.1f}%" if c['total'] > 0 else "N/A"
        note = "*" if cat == 'accessibility' and c['failed'] == c['total'] else ""
        report += f"| {label} | {c['total']} | {c['passed']} | {c['failed']} | {rate}{note} |\n"
    report += f"| **Total** | **{total}** | **{v_passed}** | **{v_failed}** | **{100*v_passed/total:.1f}%** |\n"

    if acc_false_neg > 0:
        report += f"\n*Accessibility failures are due to a constraint engine limitation — see notes below.\n"

    report += "\n---\n\n## Failures\n\n"

    # Failures grouped by category
    failures = [r for r in visual_results if not r.get('pass')]
    if failures:
        fail_by_cat = {}
        for r in failures:
            rule = next((rl for rl in rules if rl['name'] == r['name']), None)
            cat = rule['category'] if rule else 'unknown'
            fail_by_cat.setdefault(cat, []).append({**r, 'selector': rule['selector'] if rule else ''})

        for cat, fails in fail_by_cat.items():
            label = cat.replace('-', ' ').title()
            report += f"### {label} ({len(fails)} failure{'s' if len(fails) != 1 else ''})\n\n"
            report += "| Rule | Selector | Expected | Actual | Analysis |\n|------|----------|----------|--------|----------|\n"
            for f in fails:
                actual = f.get('actual', '')
                expected = f.get('expected', '')
                analysis = _get_analysis(f['name'], expected, actual)
                report += f"| {f['name']} | `{f['selector']}` | `{expected}` | `{actual}` | {analysis} |\n"
            report += "\n"
    else:
        report += "No failures.\n\n"

    # Passing highlights
    report += """---

## Passing Highlights

"""
    passing_cats = [cat for cat, c in cats.items() if c['failed'] == 0 and cat != 'accessibility']
    for cat in passing_cats:
        label = cat.replace('-', ' ').title()
        report += f"- **{label}** — all {cats[cat]['total']} rules pass\n"
    report += "\n"

    # Screenshot
    report += """---

## Screenshot

![Overview](screenshots/overview.png)

"""

    # Flow verification
    f_passed = sum(1 for f in flow_results if f['pass'])
    f_failed = len(flow_results) - f_passed

    report += f"""---

## Flow Verification Summary

| Flow | Type | Status | Report | Screenshot |
|------|------|--------|--------|------------|
"""
    for f in flow_results:
        status = 'PASS' if f['pass'] else 'FAIL'
        flow_type = f.get('type', 'state_completeness')
        report += f"| {f['name']} | {flow_type} | {status} | [{f['name']}.report.md](flow-reports/{f['name']}.report.md) | — |\n"

    if flow_results:
        report += f"\n**Result: {f_passed}/{len(flow_results)} flows pass**\n\n"
    else:
        report += "\nNo flows defined.\n\n"

    # Write individual flow report files
    for f in flow_results:
        _write_flow_report(report_dir, f, app_url)

    # Notes
    report += f"""---

## Notes

- Excluding accessibility false negatives, the effective pass rate is **{effective_rate}**.
- The `exists` constraint checks if the property value equals "exists" — it does not check element presence. All semantic landmarks ARE present in the DOM.
- `line-height` and `margin-left: auto` failures are constraint engine limitations (computed values resolve to pixels).
"""

    report_path = report_dir / 'report.md'
    report_path.write_text(report)

    # Move screenshots into report directory
    screenshots_dir = Path(app_dir) / '.ui-verification' / 'reports' / '_pending_screenshots'
    report_screenshots = report_dir / 'screenshots'
    if screenshots_dir.exists():
        report_screenshots.mkdir(exist_ok=True)
        for img in screenshots_dir.glob('*.png'):
            img.rename(report_screenshots / img.name)
        try:
            screenshots_dir.rmdir()
        except:
            pass

    rel_path = f".ui-verification/reports/{ts}/report.md"
    print(f"[done] Report: {report_path}", file=sys.stderr)
    return rel_path


def _write_flow_report(report_dir, flow, app_url):
    """Write an individual flow report file matching the ui-verification skill format"""
    flow_reports_dir = report_dir / 'flow-reports'
    flow_reports_dir.mkdir(parents=True, exist_ok=True)

    status = 'PASS' if flow['pass'] else 'FAIL'
    flow_type = flow.get('type', 'state_completeness')
    feature_title = flow.get('feature_title', flow['name'])
    scenario_title = flow.get('scenario_title', 'Verification scenario')
    run_date = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

    fr = f"""# Flow Report: {flow['name']}

**Flow:** {flow['name']} — {feature_title}  
**Type:** {flow_type}  
**URL:** {app_url}  
**Status:** {status}  
**Run date:** {run_date}

---

## Scenario: {scenario_title}

| Step | Type | Action/Assertion | Result |
|------|------|------------------|--------|
"""
    for s in flow['steps']:
        stype = s.get('type', 'then').capitalize()
        result = 'PASS' if s['pass'] else 'FAIL'
        if stype in ('Given', 'When'):
            result = 'OK' if s['pass'] else 'FAIL'
        fr += f"| {s['step'][:60]} | {stype} | {s['step']} | {result} |\n"

    passed_count = sum(1 for s in flow['steps'] if s['pass'])
    total_count = len(flow['steps'])

    if flow['pass']:
        fr += f"\n**All {total_count} assertions passed.**\n"
    else:
        fr += f"\n**{passed_count}/{total_count} assertions passed.**\n"

    # Check for failures and add details
    failures = [s for s in flow['steps'] if not s['pass']]
    if failures:
        fr += "\n---\n\n## Failures\n\n"
        for s in failures:
            fr += f"- ❌ **{s['step']}**\n"
        fr += "\n"

    flow_report_path = flow_reports_dir / f"{flow['name']}.report.md"
    flow_report_path.write_text(fr)
    print(f"[flow] Wrote {flow_report_path}", file=sys.stderr)


def _get_analysis(name, expected, actual):
    """Generate a brief analysis for a failure"""
    if 'line height' in name.lower() and 'px' in actual:
        return "Computed value resolves unitless to px"
    if 'margin' in name.lower() and expected == '=auto' and 'px' in actual:
        return "Computed resolves auto to px (element is centered)"
    if 'exists' in expected:
        return "Constraint engine limitation — element IS present"
    if 'color' in name.lower():
        return "Color mismatch — may be intentional change"
    return "Value differs from spec"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--app-dir', required=True)
    parser.add_argument('--url', required=True)
    args = parser.parse_args()

    rules = load_rules(args.app_dir)
    flows = load_flows(args.app_dir)

    if not rules and not flows:
        print("[error] No rules or flows found", file=sys.stderr)
        sys.exit(1)

    visual_results, flow_results = run_verification(args.url, args.app_dir, rules, flows)
    report_path = write_report(args.app_dir, args.url, rules, visual_results, flow_results)
    print(json.dumps({'ok': True, 'report': report_path}))


if __name__ == '__main__':
    main()
