// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/* Background service worker — handles screenshots and downloads */

chrome.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
  if (msg.action === "captureTab") {
    chrome.tabs.captureVisibleTab(null, { format: "png" }, function (dataUrl) {
      sendResponse({ dataUrl: dataUrl || null });
    });
    return true;
  }

  if (msg.action === "download") {
    chrome.downloads.download({
      url: msg.dataUrl,
      filename: msg.filename,
      saveAs: msg.saveAs || false
    });
  }
});
