// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/* Nova Act Annotator — Chrome Extension Content Script (entry point) */
(function () {
  "use strict";

  if (window.__annot_injected && window.__annot_version === 6) return;
  window.__annot_injected = true;
  window.__annot_version = 6;

  var U = window.__annotNS.utils;
  var I = window.__annotNS.inspector;
  var NC = window.__annotNS.noteComposer;
  var EC = window.__annotNS.exportChecklist;
  var H = window.__annotNS.handoff;

  // ── Configuration ──
  var CONFIG = {
    APP_NAME: "Nova Act Annotator",
    COLORS: {
      PRIMARY: "#5A969E",
      PRIMARY_HOVER: "#4A7D84",
      PRIMARY_RGBA: "rgba(90,150,158,",
      DARK_BG: "#0F1111",
      SURFACE: "#1A1A1A",
      BORDER: "#2D3A4A",
      BORDER_LIGHT: "rgba(90,150,158,0.35)",
      TEXT_PRIMARY: "#E8E8E8",
      TEXT_MUTED: "#6C7778",
      TEXT_CODE: "#AAAAAA",
      ERROR: "#FF6B6B",
      SUCCESS: "#2BB534"
    },
    SIZES: {
      SIDEBAR_WIDTH: 320,
      BUBBLE_WIDTH: 220,
      PIN_OUTER: 36,
      PIN_INNER: 28,
      PIN_OFFSET: 22,
      PIN_OVERLAP_THRESHOLD: 20
    }
  };

  // ── Shared state ──
  var state = {
    CONFIG: CONFIG,
    active: false,
    annotations: [],
    pendingPin: null,
    hoveredElement: null,
    highlightOverlay: null,
    tooltipEl: null,
    freehandPoints: [],
    isDrawingFreehand: false,
    drawOverlay: null,
    freehandCanvas: null,
    freehandCtx: null,
    pinsContainer: null,
    sidebarEl: null,
    sessionId: "",
    screenshotDataUrl: null,
    captureScrollX: 0,
    captureScrollY: 0,
    activeModes: new Set(["inspect"]),
    highlightedDrawIndex: -1
  };

  // ── Bound event handlers (for add/remove) ──
  function onDrawMouseDown(e) { I.onDrawMouseDown(e, state); }
  function onDrawMouseMove(e) { I.onDrawMouseMove(e, state); }
  function onDrawMouseUp(e) { I.onDrawMouseUp(e, state); }
  function onInspectMouseMove(e) { I.onInspectMouseMove(e, state); }
  function onInspectClick(e) { I.onInspectClick(e, state); }
  function onKeyDown(e) { I.onKeyDown(e, state); }

  function onResize() {
    if (state.freehandCanvas) {
      state.freehandCanvas.width = Math.max(window.innerWidth, document.documentElement.scrollWidth);
      state.freehandCanvas.height = Math.max(window.innerHeight, document.documentElement.scrollHeight);
      I.redrawFreehand(state);
    }
  }

  // ── State methods used by sub-modules ──
  state.updateDrawOverlay = function () {
    if (!state.drawOverlay) return;
    state.drawOverlay.style.display = (state.activeModes.has("draw") && !state.pendingPin) ? "block" : "none";
  };

  state.renderSidebar = function () { I.renderSidebar(state); };

  state.showExportChecklist = function () { EC.showExportChecklist(state); };

  state.teardown = teardown;

  state.removeEventListeners = function () {
    document.removeEventListener("mousemove", onInspectMouseMove, true);
    document.removeEventListener("click", onInspectClick, true);
    document.removeEventListener("keydown", onKeyDown, true);
    window.removeEventListener("resize", onResize);
  };

  // ── Setup ──
  function setup() {
    if (state.active) return;
    state.active = true;
    if (!state.sessionId) state.sessionId = U.uuid();
    state.screenshotDataUrl = null;
    U.injectFonts();

    state.pinsContainer = document.createElement("div");
    state.pinsContainer.id = "annot-pins";
    document.body.appendChild(state.pinsContainer);

    state.highlightOverlay = document.createElement("div");
    state.highlightOverlay.id = "annot-highlight";
    document.body.appendChild(state.highlightOverlay);

    state.freehandCanvas = document.createElement("canvas");
    state.freehandCanvas.id = "annot-freehand-canvas";
    state.freehandCanvas.width = Math.max(window.innerWidth, document.documentElement.scrollWidth);
    state.freehandCanvas.height = Math.max(window.innerHeight, document.documentElement.scrollHeight);
    document.body.appendChild(state.freehandCanvas);
    state.freehandCtx = state.freehandCanvas.getContext("2d");

    state.drawOverlay = document.createElement("div");
    state.drawOverlay.id = "annot-draw-overlay";
    document.body.appendChild(state.drawOverlay);
    state.updateDrawOverlay();

    state.sidebarEl = document.createElement("div");
    state.sidebarEl.id = "annot-sidebar";

    // Sidebar position state
    var sidebarOnLeft = false;

    function applySidebarPosition() {
      if (sidebarOnLeft) {
        state.sidebarEl.classList.add("annot-sidebar-left");
      } else {
        state.sidebarEl.classList.remove("annot-sidebar-left");
      }
      if (sidebarOnLeft) sidebarTab.classList.add("tab-left");
      else sidebarTab.classList.remove("tab-left");
    }

    // Sidebar tab
    var sidebarTab = document.createElement("div");
    sidebarTab.id = "annot-sidebar-tab";
    var tabIcon = document.createElement("img");
    tabIcon.src = chrome.runtime.getURL("icons/pin.png");
    tabIcon.className = "annot-tab-icon";
    sidebarTab.appendChild(tabIcon);
    sidebarTab.addEventListener("click", function () { I.expandSidebar(state); });
    document.body.appendChild(sidebarTab);

    // Header
    var sidebarHeader = document.createElement("div");
    sidebarHeader.className = "annot-sidebar-header";
    var headerTitle = document.createElement("span");
    headerTitle.textContent = CONFIG.APP_NAME;
    var headerActions = document.createElement("div");
    headerActions.style.cssText = "display:flex;align-items:center;gap:8px;";
    var posToggle = document.createElement("img");
    posToggle.src = chrome.runtime.getURL("icons/back.png");
    posToggle.style.cssText = "width:14px;height:14px;opacity:0.6;cursor:pointer;transform:scaleX(1);";
    posToggle.title = "Move to left";
    posToggle.addEventListener("click", function () {
      sidebarOnLeft = !sidebarOnLeft;
      applySidebarPosition();
      posToggle.style.transform = sidebarOnLeft ? "scaleX(-1)" : "scaleX(1)";
      posToggle.title = sidebarOnLeft ? "Move to right" : "Move to left";
    });
    var minimizeBtn = document.createElement("span");
    minimizeBtn.style.cssText = "cursor:pointer;font-size:18px;color:#6C7778;line-height:1;font-weight:700;";
    minimizeBtn.textContent = "–";
    minimizeBtn.title = "Minimize panel";
    minimizeBtn.addEventListener("mouseenter", function () { minimizeBtn.style.color = "#E8E8E8"; });
    minimizeBtn.addEventListener("mouseleave", function () { minimizeBtn.style.color = "#6C7778"; });
    minimizeBtn.addEventListener("click", function () { I.collapseSidebar(state); });
    var closeBtn = document.createElement("span");
    closeBtn.className = "annot-sidebar-close";
    var closeImg = document.createElement("img");
    closeImg.src = chrome.runtime.getURL("icons/x.png");
    closeImg.style.cssText = "width:14px;height:14px;opacity:0.7;";
    closeBtn.appendChild(closeImg);
    closeBtn.addEventListener("click", function () { teardown(); });
    headerActions.appendChild(posToggle);
    headerActions.appendChild(minimizeBtn);
    headerActions.appendChild(closeBtn);
    sidebarHeader.appendChild(headerTitle);
    sidebarHeader.appendChild(headerActions);

    // Mode selector
    var modeBar = document.createElement("div");
    modeBar.className = "annot-sidebar-modes";
    var modeIcons = { draw: "draw.png", element: "pick.png", pin: "pin.png" };
    ["draw", "element", "pin"].forEach(function (mode) {
      var btn = document.createElement("button");
      var modeKey = mode === "element" ? "inspect" : mode;
      btn.className = "annot-sidebar-mode-btn" + (state.activeModes.has(modeKey) ? " active" : "");
      btn.dataset.mode = mode;
      var modeIcon = document.createElement("img");
      modeIcon.src = chrome.runtime.getURL("icons/" + modeIcons[mode]);
      modeIcon.style.cssText = "width:14px;height:14px;opacity:0.7;";
      btn.appendChild(modeIcon);
      btn.appendChild(document.createTextNode(mode.charAt(0).toUpperCase() + mode.slice(1)));
      btn.addEventListener("click", function () {
        var newKey = mode === "element" ? "inspect" : mode;
        if (state.activeModes.has(newKey)) {
          state.activeModes.clear();
        } else {
          state.activeModes.clear();
          state.activeModes.add(newKey);
        }
        state.updateDrawOverlay();
        I.renderSidebarModes(state);
      });
      modeBar.appendChild(btn);
    });

    // Notes label
    var notesLabel = document.createElement("div");
    notesLabel.className = "annot-sidebar-notes-label";
    notesLabel.textContent = "Notes · 0";

    // List
    var sidebarList = document.createElement("ul");
    sidebarList.className = "annot-sidebar-list";

    // Export button
    var exportBtn = document.createElement("button");
    exportBtn.className = "annot-sidebar-export disabled";
    exportBtn.textContent = "Save & export";
    exportBtn.addEventListener("click", function () {
      if (state.annotations.length === 0) return;
      EC.showExportChecklist(state);
    });

    state.sidebarEl.appendChild(sidebarHeader);
    var modeWrap = document.createElement("div"); modeWrap.className = "annot-sidebar-modes-wrap";
    modeWrap.appendChild(modeBar);
    state.sidebarEl.appendChild(modeWrap);
    state.sidebarEl.appendChild(notesLabel);
    state.sidebarEl.appendChild(sidebarList);
    state.sidebarEl.appendChild(exportBtn);
   // Add code here
    document.body.appendChild(state.sidebarEl);

    state.drawOverlay.addEventListener("mousedown", onDrawMouseDown);
    state.drawOverlay.addEventListener("mousemove", onDrawMouseMove);
    state.drawOverlay.addEventListener("mouseup", onDrawMouseUp);
    document.addEventListener("mousemove", onInspectMouseMove, true);
    document.addEventListener("click", onInspectClick, true);
    document.addEventListener("keydown", onKeyDown, true);
    window.addEventListener("resize", onResize);

    captureScreenshot();
    I.renderPins(state);
    I.renderSidebar(state);
  }

  // ── Teardown ──
  function teardown() {
    if (!state.active) return;
    state.active = false;
    if (state.drawOverlay) { state.drawOverlay.remove(); state.drawOverlay = null; }
    state.removeEventListeners();
    if (state.pinsContainer) { state.pinsContainer.remove(); state.pinsContainer = null; }
    if (state.highlightOverlay) { state.highlightOverlay.remove(); state.highlightOverlay = null; }
    if (state.freehandCanvas) { state.freehandCanvas.remove(); state.freehandCanvas = null; state.freehandCtx = null; }
    if (state.sidebarEl) { state.sidebarEl.remove(); state.sidebarEl = null; }
    var tabEl = document.getElementById("annot-sidebar-tab");
    if (tabEl) tabEl.remove();
    if (state.tooltipEl) { state.tooltipEl.remove(); state.tooltipEl = null; }
    NC.closeBubbles();
    state.hoveredElement = null; state.pendingPin = null; state.freehandPoints = []; state.isDrawingFreehand = false;
    state.activeModes = new Set(["inspect"]);
    state.highlightedDrawIndex = -1;
  }

  function captureScreenshot() {
    state.captureScrollX = window.scrollX;
    state.captureScrollY = window.scrollY;
    chrome.runtime.sendMessage({ action: "captureTab" }, function (response) {
      if (response && response.dataUrl) state.screenshotDataUrl = response.dataUrl;
    });
  }

  // ── Message handler ──
  chrome.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
    switch (msg.action) {
      case "getState":
        sendResponse({ active: state.active, tool: state.activeModes.has("draw") ? "draw" : "inspect", annotationCount: state.annotations.length, modes: Array.from(state.activeModes) }); break;
      case "start":
        setup(); sendResponse({ ok: true }); break;
      case "stop":
        teardown(); sendResponse({ ok: true }); break;
      case "setModes":
        var newModes = new Set(msg.modes || []);
        if (newModes.has("draw") && newModes.has("inspect")) {
          newModes.delete("inspect");
        }
        state.activeModes = newModes;
        if (!state.activeModes.has("inspect")) { I.hideHighlight(state); I.removeTooltip(state); state.hoveredElement = null; }
        state.updateDrawOverlay();
        sendResponse({ ok: true, modes: Array.from(state.activeModes) }); break;
      case "export":
        EC.buildExport(state, function (result) { sendResponse(result); }); break;
      default:
        sendResponse({ error: "unknown action" });
    }
    return true;
  });
})();
