// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/* Nova Act Annotator — Inspector (sidebar dock + annotation interaction handlers) */
window.__annotNS = window.__annotNS || {};
window.__annotNS.inspector = (function () {
  "use strict";

  var U = window.__annotNS.utils;
  var S = window.__annotNS.shapes;
  var NC = window.__annotNS.noteComposer;

  // ── Pin creation and rendering ──
  function createPin(x, y, num, pinsContainer) {
    var pin = document.createElement("div"); pin.className = "annot-pin";
    pin.style.left = x + "px"; pin.style.top = y + "px";
    var icon = document.createElement("div"); icon.className = "annot-pin-icon";
    var number = document.createElement("div"); number.className = "annot-pin-number"; number.textContent = String(num);
    icon.appendChild(number); pin.appendChild(icon);
    if (pinsContainer) pinsContainer.appendChild(pin);
    return pin;
  }

  function renderPins(state) {
    if (!state.pinsContainer) return;
    state.pinsContainer.replaceChildren();
    state.annotations.forEach(function (ann, i) {
      var px = ann.rect.x, py = ann.rect.y;
      var offset = 0;
      for (var j = 0; j < i; j++) {
        if (Math.abs(state.annotations[j].rect.x - px) < state.CONFIG.SIZES.PIN_OVERLAP_THRESHOLD &&
            Math.abs(state.annotations[j].rect.y - py) < state.CONFIG.SIZES.PIN_OVERLAP_THRESHOLD) {
          offset++;
        }
      }
      var pinX = px + offset * state.CONFIG.SIZES.PIN_OFFSET;
      var pinY = py;
      var pin = createPin(pinX, pinY, i + 1, state.pinsContainer);
      pin.addEventListener("click", function (e) { e.stopPropagation(); e.preventDefault(); NC.showReadOnlyBubble(ann, pin, state); });
      if (ann.strokes) {
        pin.addEventListener("mouseenter", function () { highlightDraw(i, state); });
        pin.addEventListener("mouseleave", function () { unhighlightDraw(state); });
      } else if (ann.rect && ann.rect.w > 0) {
        pin.addEventListener("mouseenter", function () { highlightElement(ann, i, state); });
        pin.addEventListener("mouseleave", function () { unhighlightElement(state); });
      }
    });
  }

  // ── Drawing/inspect event handlers ──
  function onDrawMouseDown(e, state) {
    if (!state.active || !state.activeModes.has("draw")) return;
    if (state.pendingPin) resolvePending(state);
    NC.closeBubbles();
    state.isDrawingFreehand = true;
    state.freehandPoints = [{ x: e.pageX, y: e.pageY }];
    e.preventDefault(); e.stopPropagation();
  }

  function onDrawMouseMove(e, state) {
    if (!state.isDrawingFreehand) return;
    state.freehandPoints.push({ x: e.pageX, y: e.pageY });
    redrawFreehand(state);
  }

  function onDrawMouseUp(e, state) {
    if (!state.isDrawingFreehand) return;
    state.isDrawingFreehand = false;
    if (state.freehandPoints.length < 3) { state.freehandPoints = []; redrawFreehand(state); return; }
    var cx = 0, cy = 0;
    state.freehandPoints.forEach(function (p) { cx += p.x; cy += p.y; });
    cx = Math.round(cx / state.freehandPoints.length); cy = Math.round(cy / state.freehandPoints.length);
    var minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    state.freehandPoints.forEach(function (p) {
      if (p.x < minX) minX = p.x; if (p.y < minY) minY = p.y;
      if (p.x > maxX) maxX = p.x; if (p.y > maxY) maxY = p.y;
    });
    var sc = state.freehandPoints.slice();
    var pin = createPin(cx, cy, state.annotations.length + 1, state.pinsContainer);
    state.pendingPin = {
      el: pin,
      body: {
        rect: { x: minX, y: minY, w: maxX - minX, h: maxY - minY },
        strokes: sc,
        selector: "",
        element_styles: null
      }
    };
    state.freehandPoints = []; redrawFreehand(state); drawStrokes(sc, "rgba(90,150,158,0.85)", 3, state);
    state.updateDrawOverlay();
    NC.showNewBubble(pin, state.pendingPin.body, state);
  }

  function onInspectMouseMove(e, state) {
    if (!state.active) return;
    if (!state.activeModes.has("inspect") && !state.activeModes.has("pin")) return;
    if (state.activeModes.has("pin")) { hideHighlight(state); removeTooltip(state); return; }
    var el = document.elementFromPoint(e.clientX, e.clientY);
    if (el && !isOurElement(el)) {
      if (el !== state.hoveredElement) { state.hoveredElement = el; showHighlight(el, state); showTooltip(el, e, state); }
      else if (state.tooltipEl) { state.tooltipEl.style.left = (e.pageX + 12) + "px"; state.tooltipEl.style.top = Math.max(0, (e.pageY - 22)) + "px"; }
    } else { state.hoveredElement = null; hideHighlight(state); removeTooltip(state); }
  }

  function onInspectClick(e, state) {
    if (!state.active) return;
    if (!state.activeModes.has("inspect") && !state.activeModes.has("pin")) return;
    if (isOurElement(e.target)) return;
    if (state.pendingPin) resolvePending(state);
    e.preventDefault(); e.stopPropagation();
    NC.closeBubbles(); removeTooltip(state); hideHighlight(state); state.hoveredElement = null;
    var absX = Math.round(e.pageX);
    var absY = Math.round(e.pageY);
    var el = document.elementFromPoint(e.clientX, e.clientY);
    var body;
    if (state.activeModes.has("pin") || !el || isOurElement(el)) {
      var pin = createPin(absX, absY, state.annotations.length + 1, state.pinsContainer);
      body = {
        rect: { x: absX, y: absY, w: 0, h: 0 },
        selector: "",
        tag: "",
        elId: "",
        classes: "",
        textContent: "",
        dataAttrs: {},
        element_styles: null,
        strokes: null
      };
      state.pendingPin = { el: pin, body: body };
      NC.showNewBubble(pin, body, state);
    } else {
      var rect = el.getBoundingClientRect();
      absX = Math.round(rect.left + window.scrollX);
      absY = Math.round(rect.top + window.scrollY);
      var pin = createPin(absX, absY, state.annotations.length + 1, state.pinsContainer);
      body = {
        rect: { x: absX, y: absY, w: Math.round(rect.width), h: Math.round(rect.height) },
        selector: U.selectorPath(el),
        tag: el.tagName.toLowerCase(),
        elId: el.id || "",
        classes: typeof el.className === "string" ? el.className : "",
        textContent: U.textPreview(el),
        dataAttrs: U.getDataAttrs(el),
        element_styles: U.getComputedStyles(el),
        strokes: null
      };
      state.pendingPin = { el: pin, body: body };
      NC.showNewBubble(pin, body, state);
    }
  }

  function onKeyDown(e, state) {
    if (state.active && e.key === "Escape" && state.pendingPin) cancelPending(state);
  }

  function isOurElement(el) {
    if (!el) return false;
    return el.closest && (el.closest("#annot-pins") || el.closest("#annot-highlight") || el.closest(".annot-tooltip") || el.closest(".annot-bubble") || el.closest("#annot-sidebar") || el.closest("#annot-sidebar-tab") || el.id === "annot-freehand-canvas" || el.id === "annot-draw-overlay");
  }

  // ── Submit / cancel ──
  function submitPending(feedback, state) {
    if (!state.pendingPin) return;
    var body = state.pendingPin.body;
    var entry = {
      id: U.uuid(),
      tag: body.tag || "",
      elId: body.elId || "",
      classes: body.classes || "",
      textContent: body.textContent || "",
      dataAttrs: body.dataAttrs || {},
      selector: body.selector || "",
      rect: body.rect,
      feedback: feedback || "",
      timestamp: new Date().toISOString(),
      url: location.href,
      drawing: body.strokes ? (function () {
        var r = S.recognizeShape(body.strokes);
        return { strokes: r.simplified, recognized_shape: r.shape, shape_confidence: r.confidence, shape_bounds: r.bounds };
      })() : null,
      strokes: body.strokes,
      element_styles: body.element_styles || null
    };
    state.annotations.push(entry);
    cleanupPending(state); renderPins(state); redrawFreehand(state); state.updateDrawOverlay(); state.renderSidebar(); notifyCount();
  }

  function resolvePending(state) {
    if (!state.pendingPin) return;
    var bubble = document.querySelector(".annot-bubble");
    var ta = bubble ? bubble.querySelector("textarea") : null;
    var text = ta ? ta.value.trim() : "";
    if (text) {
      submitPending(text, state);
    } else {
      cancelPending(state);
    }
  }

  function cancelPending(state) {
    if (state.pendingPin && state.pendingPin.el) state.pendingPin.el.remove();
    state.pendingPin = null; state.freehandPoints = []; state.isDrawingFreehand = false;
    NC.closeBubbles(); redrawFreehand(state); state.updateDrawOverlay();
  }

  function cleanupPending(state) {
    if (state.pendingPin && state.pendingPin.el) state.pendingPin.el.remove();
    state.pendingPin = null;
  }

  function notifyCount() {}

  // ── Highlight helpers ──
  function showHighlight(el, state) {
    if (!state.highlightOverlay) return;
    var rect = el.getBoundingClientRect();
    state.highlightOverlay.style.display = "block";
    state.highlightOverlay.style.top = (rect.top + window.scrollY) + "px";
    state.highlightOverlay.style.left = (rect.left + window.scrollX) + "px";
    state.highlightOverlay.style.width = rect.width + "px";
    state.highlightOverlay.style.height = rect.height + "px";
  }

  function hideHighlight(state) {
    if (state.highlightOverlay) state.highlightOverlay.style.display = "none";
  }

  function showTooltip(el, e, state) {
    removeTooltip(state);
    state.tooltipEl = document.createElement("div");
    state.tooltipEl.className = "annot-tooltip";
    var label = U.getSelector(el);
    var rect = el.getBoundingClientRect();
    label += "  " + Math.round(rect.width) + "×" + Math.round(rect.height);
    state.tooltipEl.textContent = label;
    state.tooltipEl.style.left = (e.pageX + 12) + "px";
    state.tooltipEl.style.top = Math.max(0, (e.pageY - 22)) + "px";
    document.body.appendChild(state.tooltipEl);
  }

  function removeTooltip(state) {
    if (state.tooltipEl) { state.tooltipEl.remove(); state.tooltipEl = null; }
  }

  // ── Freehand drawing ──
  function redrawFreehand(state) {
    if (!state.freehandCtx) return;
    state.freehandCtx.clearRect(0, 0, state.freehandCanvas.width, state.freehandCanvas.height);
    state.annotations.forEach(function (ann, i) {
      if (ann.strokes) {
        var color = (i === state.highlightedDrawIndex) ? "rgba(90,150,158,1)" : "rgba(90,150,158,0.15)";
        var width = (i === state.highlightedDrawIndex) ? 3 : 2;
        drawStrokes(ann.strokes, color, width, state);
      }
    });
    if (state.isDrawingFreehand && state.freehandPoints.length >= 2) drawStrokes(state.freehandPoints, "rgba(90,150,158,0.5)", 3, state);
  }

  function drawStrokes(pts, color, lineWidth, state) {
    if (!state.freehandCtx || pts.length < 2) return;
    state.freehandCtx.beginPath(); state.freehandCtx.moveTo(pts[0].x, pts[0].y);
    for (var i = 1; i < pts.length; i++) state.freehandCtx.lineTo(pts[i].x, pts[i].y);
    state.freehandCtx.strokeStyle = color; state.freehandCtx.lineWidth = lineWidth || 3;
    state.freehandCtx.lineCap = "round"; state.freehandCtx.lineJoin = "round"; state.freehandCtx.stroke();
  }

  function highlightPin(index, state) {
    if (!state.pinsContainer) return;
    var pins = state.pinsContainer.querySelectorAll(".annot-pin");
    pins.forEach(function (p, i) { p.classList.toggle("highlighted", i === index); });
  }

  function unhighlightPin(state) {
    if (!state.pinsContainer) return;
    state.pinsContainer.querySelectorAll(".annot-pin").forEach(function (p) { p.classList.remove("highlighted"); });
  }

  function highlightDraw(index, state) {
    state.highlightedDrawIndex = index;
    redrawFreehand(state);
    highlightPin(index, state);
  }

  function unhighlightDraw(state) {
    state.highlightedDrawIndex = -1;
    redrawFreehand(state);
    unhighlightPin(state);
  }

  function highlightElement(ann, index, state) {
    if (!state.highlightOverlay || !ann.rect) return;
    state.highlightOverlay.style.display = "block";
    state.highlightOverlay.style.top = (ann.rect.y) + "px";
    state.highlightOverlay.style.left = (ann.rect.x) + "px";
    state.highlightOverlay.style.width = (ann.rect.w || 0) + "px";
    state.highlightOverlay.style.height = (ann.rect.h || 0) + "px";
    if (index !== undefined) highlightPin(index, state);
  }

  function unhighlightElement(state) {
    if (state.highlightOverlay) state.highlightOverlay.style.display = "none";
    unhighlightPin(state);
  }

  // ── Sidebar rendering ──
  function _updateTabBadge(annotations) {
    var tab = document.getElementById("annot-sidebar-tab");
    if (!tab) return;
    var existing = tab.querySelector(".annot-tab-badge");
    if (existing) existing.remove();
    if (annotations.length > 0) {
      var badge = document.createElement("span");
      badge.className = "annot-tab-badge";
      badge.textContent = String(annotations.length);
      tab.appendChild(badge);
    }
  }

  function renderSidebarModes(state) {
    if (!state.sidebarEl) return;
    var btns = state.sidebarEl.querySelectorAll(".annot-sidebar-mode-btn");
    btns.forEach(function (btn) {
      var mode = btn.dataset.mode;
      var modeKey = mode === "element" ? "inspect" : mode;
      btn.className = "annot-sidebar-mode-btn" + (state.activeModes.has(modeKey) ? " active" : "");
    });
  }

  function renderSidebar(state) {
    if (!state.sidebarEl) return;
    var notesLabel = state.sidebarEl.querySelector(".annot-sidebar-notes-label");
    if (notesLabel) notesLabel.textContent = "Notes · " + state.annotations.length;
    _updateTabBadge(state.annotations);
    var expBtn = state.sidebarEl.querySelector(".annot-sidebar-export");
    if (expBtn) {
      if (state.annotations.length > 0) expBtn.classList.remove("disabled");
      else expBtn.classList.add("disabled");
    }
    var list = state.sidebarEl.querySelector(".annot-sidebar-list");
    if (!list) return;
    list.replaceChildren();
    state.annotations.forEach(function (ann, i) {
      var li = document.createElement("li"); li.className = "annot-sidebar-item";
      var hdr = document.createElement("div"); hdr.className = "annot-sidebar-hdr";
      var badge = document.createElement("span"); badge.className = "annot-sidebar-badge"; badge.textContent = String(i + 1);
      var typeLabel = document.createElement("span"); typeLabel.className = "annot-sidebar-type";
      var typeStr = ann.selector ? "ELEMENT" : (ann.drawing ? "DRAW" : "PIN");
      typeLabel.textContent = typeStr + " · " + U.timeAgo(ann.timestamp);
      hdr.appendChild(badge); hdr.appendChild(typeLabel);
      var delX = document.createElement("span"); delX.className = "annot-sidebar-item-close"; delX.textContent = "×";
      delX.addEventListener("click", function (e) {
        e.stopPropagation();
        state.annotations = state.annotations.filter(function (a) { return a.id !== ann.id; });
        renderPins(state); redrawFreehand(state); renderSidebar(state); notifyCount();
      });
      hdr.appendChild(delX);
      li.appendChild(hdr);
      var fbInput = document.createElement("input"); fbInput.className = "annot-sidebar-feedback-input"; fbInput.type = "text";
      fbInput.value = ann.feedback || ""; fbInput.placeholder = "Add feedback...";
      fbInput.addEventListener("blur", function () {
        var val = fbInput.value.trim();
        if (!val) {
          state.annotations = state.annotations.filter(function (a) { return a.id !== ann.id; });
          NC.closeBubbles(); renderPins(state); redrawFreehand(state); renderSidebar(state); notifyCount();
        } else if (val !== ann.feedback) {
          ann.feedback = val;
          var openTa = document.querySelector(".annot-bubble-readonly");
          if (openTa) openTa.textContent = val;
        }
      });
      fbInput.addEventListener("click", function (e) { e.stopPropagation(); });
      fbInput.addEventListener("focus", function () {
        if (ann.strokes) { highlightDraw(i, state); }
        else if (ann.rect && ann.rect.w > 0) { highlightElement(ann, i, state); }
        else { highlightPin(i, state); }
        window.scrollTo({ left: ann.rect.x - window.innerWidth / 2, top: ann.rect.y - window.innerHeight / 2, behavior: "smooth" });
        setTimeout(function () {
          var pinEl = state.pinsContainer ? state.pinsContainer.querySelector(".annot-pin:nth-child(" + (i + 1) + ")") : null;
          if (pinEl) NC.showReadOnlyBubble(ann, pinEl, state);
        }, 300);
      });
      fbInput.addEventListener("keydown", function (e) {
        if (e.key === "Enter") { fbInput.blur(); }
        if (e.key === "Escape") { fbInput.value = ann.feedback || ""; fbInput.blur(); }
      });
      li.appendChild(fbInput);
      if (ann.selector) {
        var sel = document.createElement("div"); sel.className = "annot-sidebar-selector"; sel.textContent = ann.selector;
        li.appendChild(sel);
      }
      if (ann.strokes) {
        li.addEventListener("mouseenter", function () { highlightDraw(i, state); });
        li.addEventListener("mouseleave", function () { unhighlightDraw(state); });
      } else if (ann.rect && ann.rect.w > 0) {
        li.addEventListener("mouseenter", function () { highlightElement(ann, i, state); });
        li.addEventListener("mouseleave", function () { unhighlightElement(state); });
      }
      li.addEventListener("click", function () {
        window.scrollTo({ left: ann.rect.x - window.innerWidth / 2, top: ann.rect.y - window.innerHeight / 2, behavior: "smooth" });
        setTimeout(function () {
          var pinEl = state.pinsContainer ? state.pinsContainer.querySelector(".annot-pin:nth-child(" + (i + 1) + ")") : null;
          if (pinEl) NC.showReadOnlyBubble(ann, pinEl, state);
        }, 300);
      });
      list.appendChild(li);
    });
  }

  function showSavingView(state) {
    if (!state.sidebarEl) return;
    state.sidebarEl.replaceChildren();
    state.sidebarEl.style.display = "flex";
    var hdr = document.createElement("div");
    hdr.className = "annot-sidebar-header";
    var hdrTitle = document.createElement("span");
    hdrTitle.textContent = state.CONFIG.APP_NAME;
    var hdrRight = document.createElement("div");
    hdrRight.style.cssText = "display:flex;align-items:center;gap:8px;";
    var savingDot = document.createElement("span");
    savingDot.style.cssText = "width:8px;height:8px;border-radius:50%;background:#2BB534;animation:annot-pulse 1s infinite;";
    var savingText = document.createElement("span");
    savingText.style.cssText = "font-size:12px;color:#2BB534;font-weight:600;letter-spacing:1px;text-transform:uppercase;";
    savingText.textContent = "SAVING";
    hdrRight.appendChild(savingDot);
    hdrRight.appendChild(savingText);
    hdr.appendChild(hdrTitle);
    hdr.appendChild(hdrRight);
    state.sidebarEl.appendChild(hdr);
    var body = document.createElement("div");
    body.style.cssText = "padding:16px;flex:1;display:flex;align-items:center;justify-content:center;color:#6C7778;font-size:13px;";
    body.textContent = "Preparing export...";
    state.sidebarEl.appendChild(body);
  }

  function rebuildSidebar(state) {
    if (!state.sidebarEl) return;
    state.sidebarEl.replaceChildren();
    state.sidebarEl.style.display = "flex";

    var sidebarHeader = document.createElement("div");
    sidebarHeader.className = "annot-sidebar-header";
    var headerTitle = document.createElement("span");
    headerTitle.textContent = state.CONFIG.APP_NAME;
    var headerActions = document.createElement("div");
    headerActions.style.cssText = "display:flex;align-items:center;gap:8px;";
    var closeBtn = document.createElement("span");
    closeBtn.className = "annot-sidebar-close";
    var closeImg = document.createElement("img");
    closeImg.src = chrome.runtime.getURL("icons/x.png");
    closeImg.style.cssText = "width:14px;height:14px;opacity:0.7;";
    closeBtn.appendChild(closeImg);
    closeBtn.addEventListener("click", function () { state.teardown(); });
    headerActions.appendChild(closeBtn);
    sidebarHeader.appendChild(headerTitle);
    sidebarHeader.appendChild(headerActions);
    state.sidebarEl.appendChild(sidebarHeader);

    var modeBar = document.createElement("div");
    modeBar.className = "annot-sidebar-modes";
    var modeIcons = { draw: "draw.png", element: "pick.png", pin: "pin.png" };
    ["draw", "element", "pin"].forEach(function (mode) {
      var btn = document.createElement("button");
      var modeKey = mode === "element" ? "inspect" : mode;
      btn.className = "annot-sidebar-mode-btn" + (state.activeModes.has(modeKey) ? " active" : "");
      btn.dataset.mode = mode;
      var modeIcon = document.createElement("img");
      modeIcon.src = chrome.runtime.getURL("icons/" + modeIcons[mode]);
      modeIcon.style.cssText = "width:14px;height:14px;opacity:0.7;";
      btn.appendChild(modeIcon);
      btn.appendChild(document.createTextNode(mode.charAt(0).toUpperCase() + mode.slice(1)));
      btn.addEventListener("click", function () {
        var newKey = mode === "element" ? "inspect" : mode;
        if (state.activeModes.has(newKey)) {
          state.activeModes.clear();
        } else {
          state.activeModes.clear();
          state.activeModes.add(newKey);
        }
        state.updateDrawOverlay();
        renderSidebarModes(state);
      });
      modeBar.appendChild(btn);
    });
    var modeWrap = document.createElement("div"); modeWrap.className = "annot-sidebar-modes-wrap";
    modeWrap.appendChild(modeBar);
    state.sidebarEl.appendChild(modeWrap);

    var notesLabel = document.createElement("div");
    notesLabel.className = "annot-sidebar-notes-label";
    notesLabel.textContent = "Notes · " + state.annotations.length;
    state.sidebarEl.appendChild(notesLabel);

    var sidebarList = document.createElement("ul");
    sidebarList.className = "annot-sidebar-list";
    state.sidebarEl.appendChild(sidebarList);

    var exportBtn = document.createElement("button");
    exportBtn.className = "annot-sidebar-export" + (state.annotations.length === 0 ? " disabled" : "");
    exportBtn.textContent = "Save & export";
    exportBtn.addEventListener("click", function () {
      if (state.annotations.length === 0) return;
      state.showExportChecklist();
    });
    state.sidebarEl.appendChild(exportBtn);

    renderSidebar(state);
  }

  function collapseSidebar(state) {
    state.sidebarEl.classList.add("annot-sidebar-collapsed");
    var tab = document.getElementById("annot-sidebar-tab");
    if (tab) tab.classList.add("tab-visible");
    _updateTabBadge(state.annotations);
  }

  function expandSidebar(state) {
    state.sidebarEl.classList.remove("annot-sidebar-collapsed");
    var tab = document.getElementById("annot-sidebar-tab");
    if (tab) tab.classList.remove("tab-visible");
  }

  return {
    createPin: createPin,
    renderPins: renderPins,
    onDrawMouseDown: onDrawMouseDown,
    onDrawMouseMove: onDrawMouseMove,
    onDrawMouseUp: onDrawMouseUp,
    onInspectMouseMove: onInspectMouseMove,
    onInspectClick: onInspectClick,
    onKeyDown: onKeyDown,
    isOurElement: isOurElement,
    submitPending: submitPending,
    cancelPending: cancelPending,
    resolvePending: resolvePending,
    cleanupPending: cleanupPending,
    notifyCount: notifyCount,
    highlightDraw: highlightDraw,
    unhighlightDraw: unhighlightDraw,
    highlightPin: highlightPin,
    unhighlightPin: unhighlightPin,
    highlightElement: highlightElement,
    unhighlightElement: unhighlightElement,
    redrawFreehand: redrawFreehand,
    drawStrokes: drawStrokes,
    showHighlight: showHighlight,
    hideHighlight: hideHighlight,
    showTooltip: showTooltip,
    removeTooltip: removeTooltip,
    renderSidebar: renderSidebar,
    renderSidebarModes: renderSidebarModes,
    _updateTabBadge: _updateTabBadge,
    showSavingView: showSavingView,
    rebuildSidebar: rebuildSidebar,
    collapseSidebar: collapseSidebar,
    expandSidebar: expandSidebar
  };
})();
