// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/* Nova Act Annotator — Popover Script */
(function () {
  "use strict";

  var STORAGE_KEY = "nova_act_annotator_has_run";

  // Determine variant
  chrome.storage.local.get([STORAGE_KEY], function (result) {
    if (result[STORAGE_KEY]) {
      // Returning user
      document.getElementById("first-run").classList.add("hidden");
      document.getElementById("returning").classList.remove("hidden");
    } else {
      // First-run
      document.getElementById("first-run").classList.remove("hidden");
      document.getElementById("returning").classList.add("hidden");
    }
  });

  function annotateCurrentPage() {
    chrome.storage.local.set({ [STORAGE_KEY]: true });
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      var tab = tabs[0];
      if (!tab || !tab.url || tab.url.startsWith("chrome://") || tab.url.startsWith("chrome-extension://") || tab.url.startsWith("edge://")) {
        window.close();
        return;
      }
      // Try sending message to existing content script
      chrome.tabs.sendMessage(tab.id, { action: "getState" }, function (response) {
        if (chrome.runtime.lastError || !response) {
          // Inject content scripts in order and CSS
          chrome.scripting.executeScript({
            target: { tabId: tab.id },
            files: ["utils.js", "shapes.js", "note-composer.js", "inspector.js", "export-checklist.js", "copy-prompt-handoff.js", "content.js"]
          }, function () {
            chrome.scripting.insertCSS({ target: { tabId: tab.id }, files: ["content.css"] }, function () {
              chrome.tabs.sendMessage(tab.id, { action: "start" });
              window.close();
            });
          });
        } else {
          if (!response.active) {
            chrome.tabs.sendMessage(tab.id, { action: "start" });
          }
          window.close();
        }
      });
    });
  }

  document.getElementById("cta-btn").addEventListener("click", annotateCurrentPage);
  document.getElementById("cta-btn-return").addEventListener("click", annotateCurrentPage);
  document.getElementById("popup-close").addEventListener("click", function () { window.close(); });
})();
