// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/* Nova Act Annotator — Shape recognition (RDP + classifiers) */
window.__annotNS = window.__annotNS || {};
window.__annotNS.shapes = (function () {
  "use strict";

  function _perpDist(p, a, b) {
    var dx = b.x - a.x, dy = b.y - a.y, lenSq = dx * dx + dy * dy;
    if (lenSq === 0) return Math.hypot(p.x - a.x, p.y - a.y);
    var t = Math.max(0, Math.min(1, ((p.x - a.x) * dx + (p.y - a.y) * dy) / lenSq));
    return Math.hypot(p.x - (a.x + t * dx), p.y - (a.y + t * dy));
  }

  function rdpSimplify(pts, eps) {
    if (pts.length <= 2) return pts.slice();
    var maxD = 0, maxI = 0;
    for (var i = 1; i < pts.length - 1; i++) {
      var d = _perpDist(pts[i], pts[0], pts[pts.length - 1]);
      if (d > maxD) { maxD = d; maxI = i; }
    }
    if (maxD > (eps || 3)) {
      var l = rdpSimplify(pts.slice(0, maxI + 1), eps);
      var r = rdpSimplify(pts.slice(maxI), eps);
      return l.slice(0, -1).concat(r);
    }
    return [pts[0], pts[pts.length - 1]];
  }

  function _bbox(pts) {
    var xs = pts.map(function (p) { return p.x; });
    var ys = pts.map(function (p) { return p.y; });
    var minX = Math.min.apply(null, xs), maxX = Math.max.apply(null, xs);
    var minY = Math.min.apply(null, ys), maxY = Math.max.apply(null, ys);
    return { x: minX, y: minY, width: maxX - minX, height: maxY - minY };
  }

  function _pathLen(pts) {
    var t = 0;
    for (var i = 1; i < pts.length; i++) t += Math.hypot(pts[i].x - pts[i - 1].x, pts[i].y - pts[i - 1].y);
    return t;
  }

  function _isClosed(pts) {
    if (pts.length < 3) return false;
    var bb = _bbox(pts), diag = Math.hypot(bb.width, bb.height);
    return diag > 0 && Math.hypot(pts[0].x - pts[pts.length - 1].x, pts[0].y - pts[pts.length - 1].y) / diag < 0.25;
  }

  function _classifyCircle(pts) {
    if (!_isClosed(pts) || pts.length < 8) return 0;
    var cx = 0, cy = 0;
    pts.forEach(function (p) { cx += p.x; cy += p.y; });
    cx /= pts.length; cy /= pts.length;
    var dists = pts.map(function (p) { return Math.hypot(p.x - cx, p.y - cy); });
    var avg = dists.reduce(function (a, b) { return a + b; }, 0) / dists.length;
    if (avg < 5) return 0;
    var variance = dists.reduce(function (a, d) { return a + (d - avg) * (d - avg); }, 0) / dists.length;
    var ratio = Math.sqrt(variance) / avg;
    if (ratio < 0.25) return 0.95;
    if (ratio < 0.35) return 0.7;
    if (ratio < 0.45) return 0.5;
    return 0;
  }

  function _classifyLine(pts) {
    if (pts.length < 2 || _isClosed(pts)) return 0;
    var pl = _pathLen(pts), direct = Math.hypot(pts[0].x - pts[pts.length - 1].x, pts[0].y - pts[pts.length - 1].y);
    if (direct < 10) return 0;
    var s = direct / pl;
    if (s > 0.95) return 0.95;
    if (s > 0.85) return 0.7;
    if (s > 0.75) return 0.4;
    return 0;
  }

  function _classifyArrow(pts) {
    if (_classifyLine(pts) < 0.3 || pts.length < 5) return 0;
    var tail = Math.max(1, pts.length - Math.max(3, Math.floor(pts.length / 5)));
    for (var i = tail; i < pts.length - 1; i++) {
      var v1x = pts[i].x - pts[i - 1].x, v1y = pts[i].y - pts[i - 1].y;
      var v2x = pts[i + 1].x - pts[i].x, v2y = pts[i + 1].y - pts[i].y;
      var m1 = Math.hypot(v1x, v1y), m2 = Math.hypot(v2x, v2y);
      if (m1 > 0 && m2 > 0) {
        var cos = Math.max(-1, Math.min(1, (v1x * v2x + v1y * v2y) / (m1 * m2)));
        if (Math.acos(cos) * 180 / Math.PI > 60) return Math.min(_classifyLine(pts) + 0.2, 0.85);
      }
    }
    return 0;
  }

  function _classifyRectangle(pts, bb) {
    if (pts.length < 4 || !_isClosed(pts) || bb.width < 10 || bb.height < 10) return 0;
    var aspect = Math.min(bb.width, bb.height) / Math.max(bb.width, bb.height);
    if (aspect > 0.7 && _classifyCircle(pts) > 0.4) return 0;
    var threshold = Math.max(bb.width, bb.height) * 0.15, onEdge = 0;
    pts.forEach(function (p) {
      var dl = Math.abs(p.x - bb.x), dr = Math.abs(p.x - (bb.x + bb.width));
      var dt = Math.abs(p.y - bb.y), db = Math.abs(p.y - (bb.y + bb.height));
      if (Math.min(dl, dr) < threshold || Math.min(dt, db) < threshold) onEdge++;
    });
    var r = onEdge / pts.length;
    if (r > 0.75) return 0.9;
    if (r > 0.6) return 0.7;
    if (r > 0.45) return 0.5;
    return 0;
  }

  function _classifyCrossout(pts, bb) {
    if (pts.length < 6 || _isClosed(pts) || bb.width < 15 || bb.height < 15) return 0;
    var pl = _pathLen(pts), diag = Math.hypot(bb.width, bb.height);
    if (diag === 0) return 0;
    var lr = pl / diag;
    if (lr < 1.4 || lr > 4) return 0;
    if (Math.min(bb.width, bb.height) / Math.max(bb.width, bb.height) < 0.3) return 0;
    var mid = Math.floor(pts.length / 2);
    var xRev = (pts[mid].x - pts[0].x) * (pts[pts.length - 1].x - pts[mid].x) < 0;
    var yRev = (pts[mid].y - pts[0].y) * (pts[pts.length - 1].y - pts[mid].y) < 0;
    if (xRev && yRev) return lr > 1.8 ? 0.85 : 0.6;
    if (xRev || yRev) return lr > 1.8 ? 0.5 : 0;
    return 0;
  }

  function recognizeShape(rawPts) {
    if (!rawPts || rawPts.length < 2) return { shape: "freehand", confidence: 0, simplified: rawPts || [], bounds: _bbox(rawPts || [{ x: 0, y: 0 }]) };
    var simplified = rdpSimplify(rawPts, 3), bb = _bbox(rawPts);
    var scores = {
      crossout: _classifyCrossout(rawPts, bb),
      arrow: _classifyArrow(simplified),
      rectangle: _classifyRectangle(rawPts, bb),
      circle: _classifyCircle(rawPts),
      line: _classifyLine(simplified)
    };
    var best = "freehand", bestC = 0;
    for (var k in scores) {
      if (scores[k] > bestC) { best = k; bestC = scores[k]; }
    }
    if (bestC < 0.4) { best = "freehand"; bestC = 0; }
    return { shape: best, confidence: Math.round(bestC * 100) / 100, simplified: simplified, bounds: bb };
  }

  return {
    recognizeShape: recognizeShape
  };
})();
