// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/* Nova Act Annotator — Utility functions */
window.__annotNS = window.__annotNS || {};
window.__annotNS.utils = (function () {
  "use strict";

  var CSS_PROPS = [
    "font-size", "font-weight", "font-family",
    "color", "background-color",
    "padding", "margin",
    "border", "border-radius",
    "width", "height",
    "display", "position",
    "line-height", "letter-spacing",
    "opacity", "gap"
  ];

  function uuid() {
    return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
      var r = Math.random() * 16 | 0; return (c === "x" ? r : (r & 0x3 | 0x8)).toString(16);
    });
  }

  function getComputedStyles(el) {
    var computed = window.getComputedStyle(el);
    var styles = {};
    CSS_PROPS.forEach(function (prop) {
      var val = computed.getPropertyValue(prop);
      if (val && val !== "" && val !== "none" && val !== "normal" && val !== "0px" && val !== "rgba(0, 0, 0, 0)") {
        styles[prop] = val;
      }
    });
    return styles;
  }

  function getSelector(el) {
    if (el.id) return "#" + el.id;
    var tag = el.tagName.toLowerCase();
    var cls = el.className && typeof el.className === "string" ? el.className.trim() : "";
    return cls ? tag + "." + cls.split(/\s+/).join(".") : tag;
  }

  function selectorPath(el) {
    var parts = [];
    var cur = el;
    while (cur && cur !== document.body && cur !== document.documentElement) {
      var tag = cur.tagName.toLowerCase();
      if (cur.id) {
        parts.unshift(tag + "#" + cur.id);
        break;
      }
      var cls = cur.className && typeof cur.className === "string" ? "." + cur.className.trim().split(/\s+/).join(".") : "";
      var segment = tag + cls;
      var parent = cur.parentElement;
      if (parent) {
        var siblings = parent.children;
        var sameTag = 0;
        for (var i = 0; i < siblings.length; i++) {
          if (siblings[i].tagName === cur.tagName) sameTag++;
        }
        if (sameTag > 1) {
          var idx = 1;
          var sib = cur.previousElementSibling;
          while (sib) { idx++; sib = sib.previousElementSibling; }
          segment += ":nth-child(" + idx + ")";
        }
      }
      parts.unshift(segment);
      cur = parent;
    }
    return parts.join(" > ");
  }

  function textPreview(el) {
    var text = "";
    for (var i = 0; i < el.childNodes.length; i++) {
      if (el.childNodes[i].nodeType === 3) text += el.childNodes[i].textContent;
    }
    text = text.trim();
    if (!text) text = (el.textContent || "").trim();
    return text.length > 80 ? text.substring(0, 80) + "..." : text;
  }

  function getDataAttrs(el) {
    var attrs = {};
    if (!el.dataset) return attrs;
    for (var key in el.dataset) {
      if (key === "inspector" || key.indexOf("annot") === 0) continue;
      attrs[key] = el.dataset[key];
    }
    return attrs;
  }

  function injectFonts() {
    if (document.getElementById("annot-fonts")) return;
    var style = document.createElement("style");
    style.id = "annot-fonts";
    var base = chrome.runtime.getURL("fonts/");
    style.textContent = [
      "@font-face{font-family:'Amazon Ember';src:url('" + base + "AmazonEmber_Rg.ttf')format('truetype');font-weight:400}",
      "@font-face{font-family:'Amazon Ember';src:url('" + base + "AmazonEmber-Md.ttf')format('truetype');font-weight:500}",
      "@font-face{font-family:'Amazon Ember';src:url('" + base + "AmazonEmber_Bd.ttf')format('truetype');font-weight:700}",
      "@font-face{font-family:'Amazon Ember Duospace';src:url('" + base + "AmazonEmberDuospace_Rg.ttf')format('truetype');font-weight:400}",
      "@font-face{font-family:'Amazon Ember Duospace';src:url('" + base + "AmazonEmberDuospace_Bd.ttf')format('truetype');font-weight:700}",
    ].join("\n");
    document.head.appendChild(style);
  }

  function dataUrlToUint8Array(dataUrl) {
    var base64 = dataUrl.split(",")[1];
    var binary = atob(base64);
    var arr = new Uint8Array(binary.length);
    for (var i = 0; i < binary.length; i++) arr[i] = binary.charCodeAt(i);
    return arr;
  }

  function crc32(data) {
    var table = crc32.table;
    if (!table) {
      table = crc32.table = new Uint32Array(256);
      for (var i = 0; i < 256; i++) {
        var c = i;
        for (var j = 0; j < 8; j++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
        table[i] = c;
      }
    }
    var crc = 0xFFFFFFFF;
    for (var k = 0; k < data.length; k++) crc = table[(crc ^ data[k]) & 0xFF] ^ (crc >>> 8);
    return (crc ^ 0xFFFFFFFF) >>> 0;
  }

  function createZip(files) {
    var localHeaders = [];
    var centralHeaders = [];
    var offset = 0;
    files.forEach(function (file) {
      var nameBytes = new TextEncoder().encode(file.name);
      var local = new Uint8Array(30 + nameBytes.length + file.data.length);
      var view = new DataView(local.buffer);
      view.setUint32(0, 0x04034b50, true);
      view.setUint16(4, 20, true);
      view.setUint16(6, 0, true);
      view.setUint16(8, 0, true);
      view.setUint16(10, 0, true);
      view.setUint16(12, 0, true);
      view.setUint32(14, crc32(file.data), true);
      view.setUint32(18, file.data.length, true);
      view.setUint32(22, file.data.length, true);
      view.setUint16(26, nameBytes.length, true);
      view.setUint16(28, 0, true);
      local.set(nameBytes, 30);
      local.set(file.data, 30 + nameBytes.length);
      localHeaders.push(local);

      var central = new Uint8Array(46 + nameBytes.length);
      var cv = new DataView(central.buffer);
      cv.setUint32(0, 0x02014b50, true);
      cv.setUint16(4, 20, true);
      cv.setUint16(6, 20, true);
      cv.setUint16(8, 0, true);
      cv.setUint16(10, 0, true);
      cv.setUint16(12, 0, true);
      cv.setUint16(14, 0, true);
      cv.setUint32(16, crc32(file.data), true);
      cv.setUint32(20, file.data.length, true);
      cv.setUint32(24, file.data.length, true);
      cv.setUint16(28, nameBytes.length, true);
      cv.setUint16(30, 0, true);
      cv.setUint16(32, 0, true);
      cv.setUint16(34, 0, true);
      cv.setUint16(36, 0, true);
      cv.setUint32(38, 0, true);
      cv.setUint32(42, offset, true);
      central.set(nameBytes, 46);
      centralHeaders.push(central);
      offset += local.length;
    });
    var centralOffset = offset;
    var centralSize = centralHeaders.reduce(function (s, c) { return s + c.length; }, 0);
    var eocd = new Uint8Array(22);
    var ev = new DataView(eocd.buffer);
    ev.setUint32(0, 0x06054b50, true);
    ev.setUint16(4, 0, true);
    ev.setUint16(6, 0, true);
    ev.setUint16(8, files.length, true);
    ev.setUint16(10, files.length, true);
    ev.setUint32(12, centralSize, true);
    ev.setUint32(16, centralOffset, true);
    ev.setUint16(20, 0, true);
    var total = offset + centralSize + 22;
    var result = new Uint8Array(total);
    var pos = 0;
    localHeaders.forEach(function (h) { result.set(h, pos); pos += h.length; });
    centralHeaders.forEach(function (h) { result.set(h, pos); pos += h.length; });
    result.set(eocd, pos);
    return result;
  }

  function getExportFilename() {
    var now = new Date();
    var ts = now.toISOString().replace(/[:.]/g, "-").replace("T", "_").replace("Z", "");
    return "annotations-" + ts + ".zip";
  }

  function timeAgo(ts) {
    var tsMs = typeof ts === "string" ? new Date(ts).getTime() : ts;
    var diff = Math.floor((Date.now() - tsMs) / 1000);
    if (diff < 60) return "Just Now";
    var mins = Math.floor(diff / 60);
    if (mins < 60) return mins + (mins === 1 ? " minute ago" : " minutes ago");
    var hrs = Math.floor(mins / 60);
    if (hrs < 24) return hrs + (hrs === 1 ? " hour ago" : " hours ago");
    var days = Math.floor(hrs / 24);
    if (days < 30) return days + (days === 1 ? " day ago" : " days ago");
    var months = Math.floor(days / 30);
    return months + (months === 1 ? " month ago" : " months ago");
  }

  function toToon(value, indent) {
    indent = indent || 0;
    var pad = "  ".repeat(indent);
    if (value === null || value === undefined) return "null";
    if (typeof value === "boolean" || typeof value === "number") return String(value);
    if (typeof value === "string") {
      if (value === "" || /[\n\r\t,]/.test(value) || value !== value.trim() || /^[^:]+:\s/.test(value)) return JSON.stringify(value);
      return value;
    }
    if (Array.isArray(value)) {
      if (value.length === 0) return "[]";
      if (typeof value[0] === "object" && value[0] !== null && !Array.isArray(value[0])) {
        var keys = Object.keys(value[0]);
        var uniform = value.every(function (item) {
          return typeof item === "object" && item !== null && !Array.isArray(item);
        });
        if (uniform && keys.length > 0 && keys.length <= 8) {
          var allSimple = value.every(function (item) {
            return keys.every(function (k) {
              var v = item[k];
              return v === null || v === undefined || typeof v === "string" || typeof v === "number" || typeof v === "boolean";
            });
          });
          if (allSimple) {
            var lines = [pad + keys.join(", ")];
            value.forEach(function (item) {
              var vals = keys.map(function (k) {
                var v = item[k];
                if (v === null || v === undefined) return "";
                if (typeof v === "string" && (v === "" || /[,\n\r"]/.test(v))) return JSON.stringify(v);
                return String(v);
              });
              lines.push(pad + vals.join(", "));
            });
            return lines.join("\n");
          }
        }
      }
      var items = value.map(function (item) { return pad + "- " + toToon(item, indent + 1).trimStart(); });
      return items.join("\n");
    }
    if (typeof value === "object") {
      var oKeys = Object.keys(value);
      if (oKeys.length === 0) return "{}";
      var oLines = oKeys.map(function (k) {
        var v = value[k];
        if (v && typeof v === "object" && !Array.isArray(v) && Object.keys(v).length > 0) {
          return pad + k + ":\n" + toToon(v, indent + 1);
        }
        if (Array.isArray(v) && v.length > 0) {
          return pad + k + ":\n" + toToon(v, indent + 1);
        }
        return pad + k + ": " + toToon(v, indent);
      });
      return oLines.join("\n");
    }
    return String(value);
  }

  return {
    uuid: uuid,
    getComputedStyles: getComputedStyles,
    getSelector: getSelector,
    selectorPath: selectorPath,
    textPreview: textPreview,
    getDataAttrs: getDataAttrs,
    injectFonts: injectFonts,
    dataUrlToUint8Array: dataUrlToUint8Array,
    createZip: createZip,
    getExportFilename: getExportFilename,
    timeAgo: timeAgo,
    toToon: toToon
  };
})();
