#!/usr/bin/env node
// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/**
 * proxy-worker.js — Reverse proxy with Bee completed-conversation sidebar.
 *
 * Listens for completed Bee conversations (state=processed), fetches their
 * full summary/transcript, filters for design-related content, and surfaces
 * them as actionable cards in the proxied app's sidebar.
 *
 * CLI Args:
 *   --target URL             — Upstream app server to proxy (e.g. http://localhost:5173)
 *   --port PORT              — Port to listen on (e.g. 9997)
 *   --feedback PATH          — Path to shared feedback.json file
 *   --inspector-script PATH  — Path to inspector.js to inject into HTML responses
 *   --app-dir PATH           — App workspace root for AI CLI invocations
 *   --cli CMD                — AI CLI to use (auto-detects claude or kiro-cli)
 *   --filter KEYWORDS        — Comma-separated keywords to filter conversations
 *
 * Architecture:
 *   - Proxies all HTTP requests to the target server
 *   - For HTML responses: injects inspector.js before </body>
 *   - For WebSocket upgrades: passes through for HMR support
 *   - Spawns `bee stream` subprocess listening for update-conversation events
 *   - When a conversation reaches "processed" state, fetches full details
 *   - Filters completed conversations for design-related keywords
 *   - Exposes REST APIs for the sidebar to consume
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const { spawn, exec, execSync } = require('child_process');

// ─── Argument parsing ─────────────────────────────────────────────────────────
const args = process.argv.slice(2);
let target, port, feedbackPath, inspectorScriptPath, appDir, filterKeywords, cliCmd;

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--target' && args[i + 1]) target = args[++i];
  if (args[i] === '--port' && args[i + 1]) port = parseInt(args[++i]);
  if (args[i] === '--feedback' && args[i + 1]) feedbackPath = args[++i];
  if (args[i] === '--inspector-script' && args[i + 1]) inspectorScriptPath = args[++i];
  if (args[i] === '--app-dir' && args[i + 1]) appDir = args[++i];
  if (args[i] === '--cli' && args[i + 1]) cliCmd = args[++i];
  if (args[i] === '--filter' && args[i + 1]) filterKeywords = args[++i];
}

if (!port || !feedbackPath || !inspectorScriptPath) {
  process.stderr.write(`Usage: node proxy-worker.js --target http://localhost:5173 --port 9997 --feedback .tmp/feedback.json --inspector-script ./inspector.js [--app-dir ./app] [--cli claude]

Options:
  --target              Upstream app URL to proxy (required)
  --port                Port for this proxy (required)
  --feedback            Path to store conversation feedback JSON (required)
  --inspector-script    Path to the inspector.js file (required)
  --app-dir             Your app's workspace root (default: cwd)
  --cli                 AI CLI command (auto-detects claude or kiro-cli)
  --filter              Comma-separated filter keywords
`);
  process.exit(1);
}

feedbackPath = path.resolve(feedbackPath);
inspectorScriptPath = path.resolve(inspectorScriptPath);

const FILTER_WORDS = (filterKeywords || 'design,css,color,font,layout,spacing,ui,ux,padding,margin,border,background,width,height,style,theme,responsive,mobile,animation').split(',').map(w => w.trim().toLowerCase());

// ─── CLI detection (same as agent-bridge) ─────────────────────────────────────
function detectCli() {
  if (cliCmd) return cliCmd;
  try { execSync('which claude', { stdio: 'ignore' }); return 'claude'; } catch (_) {}
  try { execSync('which kiro-cli', { stdio: 'ignore' }); return 'kiro-cli'; } catch (_) {}
  const kiroPath = (process.env.HOME || '') + '/.local/bin/kiro-cli';
  if (fs.existsSync(kiroPath)) return kiroPath;
  process.stderr.write('[bee-proxy] WARNING: No AI CLI detected. Install claude or kiro-cli.\n');
  return 'claude';
}

function buildCliCommand(cli, promptFile) {
  const file = cli.includes('kiro') ? path.resolve(promptFile) : promptFile;
  if (cli.includes('claude')) {
    return `${cli} -p "$(cat ${file})" --allowedTools Edit,Read,Bash,Write`;
  }
  if (cli.includes('kiro')) {
    return `${cli} chat -a --resume --no-interactive --effort max "$(cat ${file})"`;
  }
  return `${cli} "$(cat ${file})"`;
}

const CLI = detectCli();
const BEE_CLI = process.env.BEE_CLI_PATH || 'bee';
const EXEC_ENV = Object.assign({}, process.env, {
  PATH: process.env.PATH || '/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin',
});

process.stderr.write('[bee-proxy] Using AI CLI: ' + CLI + '\n');

// ─── Conversation buffer ──────────────────────────────────────────────────────
const MAX_CONVERSATIONS = 50;
let conversations = [];
let beeStreamStatus = 'disconnected';
let beeStreamProcess = null;
const seenConversationIds = new Set();
let sseClients = [];

function addConversation(conv) {
  if (seenConversationIds.has(conv.id)) {
    conversations = conversations.map(c => c.id === conv.id ? conv : c);
  } else {
    conversations.push(conv);
    seenConversationIds.add(conv.id);
    if (conversations.length > MAX_CONVERSATIONS) {
      const removed = conversations.shift();
      seenConversationIds.delete(removed.id);
    }
  }
  persistConversations();
  broadcastSSE({ type: 'new-conversation', conversation: conv });
}

function broadcastSSE(data) {
  const msg = 'data: ' + JSON.stringify(data) + '\n\n';
  sseClients.forEach(client => {
    try { client.write(msg); } catch (_) {}
  });
}

function persistConversations() {
  try {
    const convPath = path.join(path.dirname(feedbackPath), 'bee-conversations.json');
    fs.mkdirSync(path.dirname(convPath), { recursive: true });
    fs.writeFileSync(convPath, JSON.stringify(conversations, null, 2));
  } catch (_) {}
}

function isDesignRelated(text) {
  if (!text) return false;
  const lower = text.toLowerCase();
  return FILTER_WORDS.some(word => lower.includes(word));
}

// ─── Fetch full conversation details ──────────────────────────────────────────
function fetchConversationDetails(conversationId, callback) {
  exec(BEE_CLI + ' conversations get ' + conversationId + ' --json', { env: EXEC_ENV, timeout: 30000 }, function(err, stdout, stderr) {
    if (err) {
      process.stderr.write('[bee-conv] Failed to fetch conversation ' + conversationId + ': ' + (stderr || err.message) + '\n');
      callback(null);
      return;
    }
    try {
      const data = JSON.parse(stdout.trim());
      callback(data.conversation || data);
    } catch (e) {
      process.stderr.write('[bee-conv] Failed to parse conversation JSON: ' + e.message + '\n');
      callback(null);
    }
  });
}

function fetchConversationTranscript(conversationId, callback) {
  exec(BEE_CLI + ' conversations transcript ' + conversationId + ' --json', { env: EXEC_ENV, timeout: 30000 }, function(err, stdout, stderr) {
    if (err) {
      callback(null);
      return;
    }
    try {
      const data = JSON.parse(stdout.trim());
      callback(data.transcript || data);
    } catch (_) {
      callback(null);
    }
  });
}

// ─── Bee Stream subprocess ────────────────────────────────────────────────────
function startBeeStream() {
  if (beeStreamProcess) {
    try { beeStreamProcess.kill(); } catch (_) {}
  }

  const child = spawn(BEE_CLI, ['stream', '--types', 'update-conversation', '--json'], {
    env: EXEC_ENV,
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  beeStreamProcess = child;
  beeStreamStatus = 'connecting';
  process.stderr.write('[bee-conv] Starting bee stream (listening for completed conversations)...\n');

  let buffer = '';
  child.stdout.on('data', (data) => {
    buffer += data.toString();
    const lines = buffer.split('\n');
    buffer = lines.pop() || '';

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      try {
        const event = JSON.parse(trimmed);
        handleBeeEvent(event);
      } catch (_) {
        if (trimmed.includes('connected') || trimmed.includes('CONNECTED')) {
          beeStreamStatus = 'connected';
          process.stderr.write('[bee-conv] Bee stream connected\n');
        }
      }
    }
  });

  child.stderr.on('data', (data) => {
    const msg = data.toString().trim();
    if (msg) process.stderr.write('[bee-stream-stderr] ' + msg + '\n');
  });

  child.on('close', (code) => {
    beeStreamStatus = 'disconnected';
    process.stderr.write('[bee-conv] Bee stream disconnected (code ' + code + '), reconnecting in 5s...\n');
    beeStreamProcess = null;
    setTimeout(startBeeStream, 5000);
  });

  child.on('error', (err) => {
    beeStreamStatus = 'error: ' + err.message;
    process.stderr.write('[bee-conv] Bee stream error: ' + err.message + '\n');
    beeStreamProcess = null;
    setTimeout(startBeeStream, 10000);
  });
}

function extractKeyTakeaways(fullSummary) {
  if (!fullSummary) return [];
  const match = fullSummary.match(/## Key Take\s*aways\s*\n([\s\S]*?)(?:\n## |$)/i);
  if (!match) return [];
  return match[1].split('\n')
    .map(line => line.replace(/^[-*]\s*/, '').replace(/\*\*/g, '').trim())
    .filter(line => line.length > 0);
}

function handleBeeEvent(event) {
  beeStreamStatus = 'connected';

  if (!event.conversation) return;

  const conv = event.conversation;
  const state = (conv.state || '').toLowerCase();
  const id = conv.id || conv.uuid;

  if (!id) return;

  if (state !== 'processed' && state !== 'completed') return;

  const title = conv.title || '';
  const shortSummary = conv.short_summary || '';

  process.stderr.write('[bee-conv] Completed conversation: "' + (title || shortSummary).substring(0, 60) + '" — fetching details...\n');

  fetchConversationDetails(id, function(details) {
    const fullSummary = (details && details.summary) || '';
    const combinedText = title + ' ' + shortSummary + ' ' + fullSummary;

    if (!isDesignRelated(combinedText)) {
      process.stderr.write('[bee-conv] Skipped non-design conversation: "' + (title || shortSummary).substring(0, 60) + '"\n');
      return;
    }

    const keyTakeaways = extractKeyTakeaways(fullSummary);
    const resolvedTitle = title || (details && details.title) || (details && details.short_summary) || shortSummary;

    const conversation = {
      id: String(id),
      uuid: conv.uuid || '',
      title: resolvedTitle,
      shortSummary: (details && details.short_summary) || shortSummary,
      fullSummary: fullSummary,
      keyTakeaways: keyTakeaways,
      state: state,
      details: details,
      transcript: null,
      timestamp: Date.now(),
      applied: false,
    };

    fetchConversationTranscript(id, function(transcript) {
      conversation.transcript = transcript;
      addConversation(conversation);
      process.stderr.write('[bee-conv] Added conversation: "' + resolvedTitle.substring(0, 60) + '" with ' + keyTakeaways.length + ' takeaways\n');
    });
  });
}

// ─── Inspector script injection ───────────────────────────────────────────────
function getScriptTag() {
  var script = fs.readFileSync(inspectorScriptPath, 'utf-8');
  return '<script>' + script + '</script>';
}

const targetUrl = target ? new URL(target) : null;

// ─── HTTP Server ──────────────────────────────────────────────────────────────
const server = http.createServer((req, res) => {
  if (req.url && req.url.startsWith('/api/')) {
    if (req.method === 'OPTIONS') {
      res.writeHead(204, {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      });
      res.end();
      return;
    }
  }

  // ─── Conversations API ────────────────────────────────────────────
  if (req.url === '/api/bee/conversations') {
    if (req.method === 'GET') {
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(JSON.stringify(conversations));
    } else if (req.method === 'DELETE') {
      conversations = [];
      seenConversationIds.clear();
      persistConversations();
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end('{"ok":true}');
    } else {
      res.writeHead(405);
      res.end();
    }
    return;
  }

  if (req.url && req.url.startsWith('/api/bee/conversations/') && req.method === 'GET') {
    const convId = req.url.replace('/api/bee/conversations/', '');
    const conv = conversations.find(c => c.id === convId);
    if (conv) {
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(JSON.stringify(conv));
    } else {
      res.writeHead(404, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(JSON.stringify({ error: 'Conversation not found' }));
    }
    return;
  }

  // SSE stream
  if (req.url === '/api/bee/stream') {
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
      'Access-Control-Allow-Origin': '*',
    });
    res.write('data: ' + JSON.stringify({ type: 'connected', status: beeStreamStatus, conversationCount: conversations.length }) + '\n\n');
    sseClients.push(res);
    req.on('close', () => {
      sseClients = sseClients.filter(c => c !== res);
    });
    return;
  }

  if (req.url === '/api/bee/status') {
    res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
    res.end(JSON.stringify({ status: beeStreamStatus, conversationCount: conversations.length, filter: FILTER_WORDS }));
    return;
  }

  // ─── Retrieve latest conversations on demand ──────────────────────
  if (req.url === '/api/bee/retrieve' && req.method === 'POST') {
    exec(BEE_CLI + ' conversations list --limit 5 --json', { env: EXEC_ENV, timeout: 30000 }, function(err, stdout, stderr) {
      if (err) {
        res.writeHead(500, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
        res.end(JSON.stringify({ error: 'Failed to list conversations: ' + (stderr || err.message) }));
        return;
      }
      try {
        const data = JSON.parse(stdout.trim());
        const items = data.conversations || data.items || data || [];
        let added = 0;
        let pending = items.length;

        if (pending === 0) {
          res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ ok: true, added: 0, total: conversations.length }));
          return;
        }

        items.forEach(function(item) {
          const id = String(item.id || item.uuid);
          if (seenConversationIds.has(id)) {
            pending--;
            if (pending === 0) {
              res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
              res.end(JSON.stringify({ ok: true, added: added, total: conversations.length }));
            }
            return;
          }

          fetchConversationDetails(id, function(details) {
            const title = item.title || (details && details.title) || '';
            const shortSummary = item.short_summary || (details && details.short_summary) || '';
            const fullSummary = (details && details.summary) || '';
            const combinedText = title + ' ' + shortSummary + ' ' + fullSummary;

            if (isDesignRelated(combinedText)) {
              const keyTakeaways = extractKeyTakeaways(fullSummary);
              const conversation = {
                id: id,
                uuid: item.uuid || '',
                title: title || shortSummary || 'Untitled',
                shortSummary: shortSummary,
                fullSummary: fullSummary,
                keyTakeaways: keyTakeaways,
                state: item.state || 'processed',
                details: details,
                transcript: null,
                timestamp: Date.now(),
                applied: false,
              };

              fetchConversationTranscript(id, function(transcript) {
                conversation.transcript = transcript;
                addConversation(conversation);
                added++;
                pending--;
                if (pending === 0) {
                  res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
                  res.end(JSON.stringify({ ok: true, added: added, total: conversations.length }));
                }
              });
            } else {
              pending--;
              if (pending === 0) {
                res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
                res.end(JSON.stringify({ ok: true, added: added, total: conversations.length }));
              }
            }
          });
        });
      } catch (e) {
        res.writeHead(500, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
        res.end(JSON.stringify({ error: 'Failed to parse response: ' + e.message }));
      }
    });
    return;
  }

  // ─── Report view endpoint ──────────────────────────────────────
  if (req.url === '/api/bee/report/view') {
    const execCwd = appDir || process.cwd();
    const reportsDir = path.join(execCwd, '.ui-verification', 'reports');
    try {
      const dirs = fs.readdirSync(reportsDir).filter(d => fs.statSync(path.join(reportsDir, d)).isDirectory()).sort().reverse();
      for (const dir of dirs) {
        const rp = path.join(reportsDir, dir, 'report.md');
        if (fs.existsSync(rp)) {
          const md = fs.readFileSync(rp, 'utf-8');
          const html = '<html><head><meta charset="utf-8"><title>Verification Report</title><style>body{font-family:-apple-system,sans-serif;max-width:900px;margin:40px auto;padding:0 20px;background:#0F1111;color:#E8E8E8;line-height:1.6}h1,h2,h3{color:#5A969E}table{border-collapse:collapse;width:100%}th,td{border:1px solid #2D3A4A;padding:8px;text-align:left}th{background:#1A1A1A}code{background:#1A1A1A;padding:2px 6px;border-radius:4px;font-size:13px}pre{background:#1A1A1A;padding:16px;border-radius:8px;overflow-x:auto}</style></head><body><pre>' + md.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;') + '</pre></body></html>';
          res.writeHead(200, { 'Content-Type': 'text/html', 'Access-Control-Allow-Origin': '*' });
          res.end(html);
          return;
        }
      }
    } catch (_) {}
    res.writeHead(200, { 'Content-Type': 'text/html', 'Access-Control-Allow-Origin': '*' });
    res.end('<html><body><h1>No report found</h1><p>Run verification first.</p></body></html>');
    return;
  }

  // ─── Apply a conversation's design feedback via AI CLI ──────────
  if (req.url === '/api/bee/apply/status') {
    const statusFile = path.join(path.dirname(feedbackPath), 'bee-conv-apply-status.json');
    if (fs.existsSync(statusFile)) {
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(fs.readFileSync(statusFile, 'utf-8'));
    } else {
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end(JSON.stringify({ status: 'idle' }));
    }
    return;
  }

  if (req.url === '/api/bee/apply') {
    if (req.method === 'POST') {
      let body = '';
      req.on('data', chunk => body += chunk);
      req.on('end', () => {
        try {
          const payload = JSON.parse(body);
          const convId = payload.conversationId;
          const instruction = payload.instruction || '';

          const conv = conversations.find(c => c.id === convId);
          if (!conv && !instruction) {
            res.writeHead(400, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
            res.end(JSON.stringify({ error: 'Conversation not found and no instruction provided' }));
            return;
          }

          let feedbackText = instruction;
          if (!feedbackText && conv) {
            const parts = [];
            if (conv.title) parts.push('Topic: ' + conv.title);
            if (conv.keyTakeaways && conv.keyTakeaways.length > 0) {
              parts.push('Design decisions to implement:\n' + conv.keyTakeaways.map(t => '- ' + t).join('\n'));
            }
            if (conv.fullSummary) {
              parts.push('Full context:\n' + conv.fullSummary);
            } else if (conv.shortSummary) {
              parts.push('Summary: ' + conv.shortSummary);
            }
            if (conv.transcript && Array.isArray(conv.transcript)) {
              const designUtterances = conv.transcript
                .filter(u => isDesignRelated(u.text || ''))
                .map(u => (u.speaker || 'someone') + ': "' + (u.text || '') + '"')
                .slice(0, 10);
              if (designUtterances.length > 0) {
                parts.push('Relevant conversation excerpts:\n' + designUtterances.join('\n'));
              }
            }
            feedbackText = parts.join('\n\n');
          }

          const prompt = 'Apply the design changes from this conversation to the codebase. Focus on the "Design decisions to implement" section — these are the specific changes that were agreed upon. Search for relevant CSS/component/layout files and make the changes directly. Do not ask clarifying questions.\n\n' + feedbackText;

          const statusFile = path.join(path.dirname(feedbackPath), 'bee-conv-apply-status.json');
          fs.mkdirSync(path.dirname(statusFile), { recursive: true });
          fs.writeFileSync(statusFile, JSON.stringify({ status: 'running', timestamp: Date.now() }));

          res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ ok: true, message: 'Applying conversation feedback via ' + CLI + '...' }));

          if (conv) conv.applied = true;
          persistConversations();

          const promptFile = path.resolve(path.join(path.dirname(feedbackPath), 'bee-conv-apply-prompt.txt'));
          fs.writeFileSync(promptFile, prompt);
          const execCwd = appDir || process.cwd();

          const cmd = buildCliCommand(CLI, promptFile);
          exec(cmd, { timeout: 300000, cwd: execCwd, env: EXEC_ENV }, function(err, stdout, stderr) {
            if (err && CLI.includes('kiro') && (stderr || '').includes('No session')) {
              const retryCmd = CLI + ' chat -a --no-interactive --effort max "$(cat \'' + promptFile + '\')"';
              exec(retryCmd, { timeout: 300000, cwd: execCwd, env: EXEC_ENV }, onApplyDone);
              return;
            }
            onApplyDone(err, stdout, stderr);
          });

          function onApplyDone(err, stdout, stderr) {
            try { fs.unlinkSync(promptFile); } catch (_) {}
            if (err) {
              process.stderr.write('[bee-conv-apply] CLI failed: ' + (stderr || err.message) + '\n');
              fs.writeFileSync(statusFile, JSON.stringify({ status: 'error', error: err.message, timestamp: Date.now() }));
              return;
            }
            process.stderr.write('[bee-conv-apply] Changes applied successfully via ' + CLI + '. Checking dev server...\n');

            const appUrl = payload.url || 'http://localhost:5173';
            var attempts = 0;
            function checkServer() {
              attempts++;
              http.get(appUrl, function (r) {
                r.resume();
                if (r.statusCode >= 200 && r.statusCode < 500) {
                  process.stderr.write('[bee-conv-apply] Dev server responding (attempt ' + attempts + ')\n');
                  runVerification();
                } else if (attempts < 20) {
                  setTimeout(checkServer, 2000);
                } else {
                  runVerification();
                }
              }).on('error', function () {
                if (attempts < 20) { setTimeout(checkServer, 2000); }
                else {
                  process.stderr.write('[bee-conv-apply] Dev server not responding, skipping verification\n');
                  fs.writeFileSync(statusFile, JSON.stringify({ status: 'done', timestamp: Date.now() }));
                }
              });
            }
            checkServer();

            function runVerification() {
              process.stderr.write('[bee-conv-apply] Running verification...\n');
              fs.writeFileSync(statusFile, JSON.stringify({ status: 'verifying', timestamp: Date.now() }));

              const verifyScript = path.join(__dirname, '..', 'agent-bridge', 'verify-with-nova-act.py');
              const verifyEnv = Object.assign({}, EXEC_ENV, { NOVA_ACT_API_KEY: process.env.NOVA_ACT_API_KEY || '' });
              const venvPython = path.resolve(execCwd, '..', '.venv', 'bin', 'python3');
              const pythonBin = fs.existsSync(venvPython) ? venvPython : 'python3';
              const absAppDir = path.resolve(execCwd);
              const verifyCmd = pythonBin + ' "' + verifyScript + '" --app-dir "' + absAppDir + '" --url "' + appUrl + '"';
              process.stderr.write('[bee-conv-apply] Verify command: ' + verifyCmd + '\n');

              exec(verifyCmd, { timeout: 300000, cwd: absAppDir, env: verifyEnv }, function (err2, stdout2, stderr2) {
                if (err2) {
                  var errMsg = (stderr2 || err2.message || '').replace(/\x1B\[[0-9;]*m/g, '').trim().slice(-500);
                  process.stderr.write('[bee-conv-apply] Verification FAILED: ' + errMsg + '\n');
                  fs.writeFileSync(statusFile, JSON.stringify({ status: 'error', error: 'Verification failed: ' + errMsg, timestamp: Date.now() }));
                  return;
                }
                var report = null;
                try {
                  const result = JSON.parse((stdout2 || '').trim());
                  report = result.report || null;
                } catch (_) {
                  try {
                    const reportsDir = path.join(execCwd, '.ui-verification', 'reports');
                    if (fs.existsSync(reportsDir)) {
                      const dirs = fs.readdirSync(reportsDir).filter(d => fs.statSync(path.join(reportsDir, d)).isDirectory()).sort().reverse();
                      for (const dir of dirs) {
                        const rp = path.join(reportsDir, dir, 'report.md');
                        if (fs.existsSync(rp)) { report = '.ui-verification/reports/' + dir + '/report.md'; break; }
                      }
                    }
                  } catch (_) {}
                }
                var reportAbsPath = report ? path.join(execCwd, report) : null;
                fs.writeFileSync(statusFile, JSON.stringify({ status: 'done', report: report, reportPath: reportAbsPath, timestamp: Date.now() }));
                process.stderr.write('[bee-conv-apply] Verification complete. Report: ' + (report || 'none') + '\n');
              });
            }
          }
        } catch (err) {
          res.writeHead(400, { 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ error: err.message }));
        }
      });
    } else {
      res.writeHead(405);
      res.end();
    }
    return;
  }

  // ─── Feedback API ─────────────────────────────────────────────────
  if (req.url === '/api/feedback') {
    if (req.method === 'POST') {
      let body = '';
      req.on('data', chunk => body += chunk);
      req.on('end', () => {
        try {
          const entry = JSON.parse(body);
          let existing = [];
          if (fs.existsSync(feedbackPath)) {
            existing = JSON.parse(fs.readFileSync(feedbackPath, 'utf-8'));
          }
          existing.push(entry);
          fs.mkdirSync(path.dirname(feedbackPath), { recursive: true });
          fs.writeFileSync(feedbackPath, JSON.stringify(existing, null, 2));
          res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
          res.end('{"ok":true}');
        } catch (err) {
          res.writeHead(400, { 'Access-Control-Allow-Origin': '*' });
          res.end(JSON.stringify({ error: err.message }));
        }
      });
    } else if (req.method === 'DELETE') {
      fs.mkdirSync(path.dirname(feedbackPath), { recursive: true });
      fs.writeFileSync(feedbackPath, '[]');
      res.writeHead(200, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
      res.end('{"ok":true}');
    } else {
      res.writeHead(405);
      res.end();
    }
    return;
  }

  // ─── Reverse proxy ─────────────────────────────────────────────────
  if (!targetUrl) {
    res.writeHead(404, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'No target configured. Running in API-only mode.' }));
    return;
  }

  const options = {
    hostname: targetUrl.hostname,
    port: targetUrl.port,
    path: req.url,
    method: req.method,
    headers: Object.assign({}, req.headers, { host: targetUrl.host }),
  };

  const proxyReq = http.request(options, proxyRes => {
    const contentType = proxyRes.headers['content-type'] || '';
    if (!contentType.includes('text/html')) {
      res.writeHead(proxyRes.statusCode, proxyRes.headers);
      proxyRes.pipe(res);
      return;
    }
    const chunks = [];
    proxyRes.on('data', chunk => chunks.push(chunk));
    proxyRes.on('end', () => {
      let html = Buffer.concat(chunks).toString();
      const scriptTag = getScriptTag();
      if (html.includes('</body>')) {
        html = html.replace('</body>', scriptTag + '</body>');
      } else {
        html += scriptTag;
      }
      const headers = Object.assign({}, proxyRes.headers);
      delete headers['content-length'];
      delete headers['content-encoding'];
      headers['transfer-encoding'] = 'chunked';
      res.writeHead(proxyRes.statusCode, headers);
      res.end(html);
    });
  });

  proxyReq.on('error', err => {
    res.writeHead(502);
    res.end('Proxy error: ' + err.message);
  });
  req.pipe(proxyReq);
});

server.listen(port, () => {
  process.stderr.write('[bee-proxy] Listening on http://localhost:' + port + '\n');
  process.stderr.write('[bee-proxy] Proxying to: ' + target + '\n');
  process.stderr.write('[bee-proxy] App dir: ' + (appDir || process.cwd()) + '\n');
  process.stdout.write('READY\n');
  startBeeStream();
});

// ─── WebSocket proxy for HMR ─────────────────────────────────────────────────
server.on('upgrade', (req, socket, head) => {
  if (!targetUrl) { socket.destroy(); return; }
  const options = {
    hostname: targetUrl.hostname,
    port: targetUrl.port,
    path: req.url,
    method: req.method,
    headers: Object.assign({}, req.headers, { host: targetUrl.host }),
  };

  const proxyReq = http.request(options);
  proxyReq.on('upgrade', (proxyRes, proxySocket, proxyHead) => {
    socket.write(
      'HTTP/1.1 101 Switching Protocols\r\n' +
      Object.entries(proxyRes.headers).map(([k, v]) => k + ': ' + v).join('\r\n') +
      '\r\n\r\n'
    );
    if (proxyHead.length) socket.write(proxyHead);
    proxySocket.pipe(socket);
    socket.pipe(proxySocket);
  });
  proxyReq.on('error', () => socket.destroy());
  proxyReq.end();
});

// ─── Cleanup ──────────────────────────────────────────────────────────────────
process.on('exit', () => {
  if (beeStreamProcess) {
    try { beeStreamProcess.kill(); } catch (_) {}
  }
});
process.on('SIGTERM', () => process.exit(0));
process.on('SIGINT', () => process.exit(0));
