// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
/**
 * Tests for the Chrome extension content script logic.
 *
 * Tests the extracted utility functions: origin validation, selector path
 * generation, text preview, data attribute extraction, and export format.
 *
 * @jest-environment jsdom
 */

// Extract testable functions from content.js by evaluating the relevant parts
// We re-implement them identically here to test the logic in isolation.

function isProxyOrigin(hostname) {
  return hostname === 'localhost' || hostname === '127.0.0.1';
}

function selectorPath(el) {
  var parts = [];
  var cur = el;
  while (cur && cur !== document.body && cur !== document.documentElement) {
    var tag = cur.tagName.toLowerCase();
    if (cur.id) {
      parts.unshift(tag + '#' + cur.id);
      break;
    }
    var cls = cur.className && typeof cur.className === 'string' ? '.' + cur.className.trim().split(/\s+/).join('.') : '';
    var segment = tag + cls;
    var parent = cur.parentElement;
    if (parent) {
      var siblings = parent.children;
      var sameTag = 0;
      for (var i = 0; i < siblings.length; i++) {
        if (siblings[i].tagName === cur.tagName) sameTag++;
      }
      if (sameTag > 1) {
        var idx = 1;
        var sib = cur.previousElementSibling;
        while (sib) { idx++; sib = sib.previousElementSibling; }
        segment += ':nth-child(' + idx + ')';
      }
    }
    parts.unshift(segment);
    cur = parent;
  }
  return parts.join(' > ');
}

function textPreview(el) {
  var text = '';
  for (var i = 0; i < el.childNodes.length; i++) {
    if (el.childNodes[i].nodeType === 3) text += el.childNodes[i].textContent;
  }
  text = text.trim();
  if (!text) text = (el.textContent || '').trim();
  return text.length > 80 ? text.substring(0, 80) + '...' : text;
}

function getDataAttrs(el) {
  var attrs = {};
  if (!el.dataset) return attrs;
  for (var key in el.dataset) {
    if (key === 'inspector' || key.indexOf('vannot') === 0) continue;
    attrs[key] = el.dataset[key];
  }
  return attrs;
}

function getComputedStyles(el) {
  var CSS_PROPS = [
    'font-size', 'font-weight', 'font-family', 'color', 'background-color',
    'padding', 'margin', 'border', 'border-radius', 'width', 'height',
    'display', 'position', 'line-height', 'letter-spacing', 'opacity', 'gap'
  ];
  var computed = window.getComputedStyle(el);
  var styles = {};
  CSS_PROPS.forEach(function(prop) {
    var val = computed.getPropertyValue(prop);
    if (val && val !== '' && val !== 'none' && val !== 'normal' && val !== '0px' && val !== 'rgba(0, 0, 0, 0)') {
      styles[prop] = val;
    }
  });
  return styles;
}

describe('isProxyOrigin', () => {
  test('allows localhost', () => {
    expect(isProxyOrigin('localhost')).toBe(true);
  });

  test('allows 127.0.0.1', () => {
    expect(isProxyOrigin('127.0.0.1')).toBe(true);
  });

  test('rejects external domains', () => {
    expect(isProxyOrigin('example.com')).toBe(false);
  });

  test('rejects localhost.evil.com', () => {
    expect(isProxyOrigin('localhost.evil.com')).toBe(false);
  });

  test('rejects 127.0.0.1.evil.com', () => {
    expect(isProxyOrigin('127.0.0.1.evil.com')).toBe(false);
  });

  test('rejects empty string', () => {
    expect(isProxyOrigin('')).toBe(false);
  });

  test('rejects localhost with port in hostname', () => {
    expect(isProxyOrigin('localhost:3000')).toBe(false);
  });
});

describe('selectorPath', () => {
  test('simple element with id', () => {
    document.body.innerHTML = '<div id="main"><span>text</span></div>';
    const span = document.querySelector('span');
    expect(selectorPath(span)).toBe('div#main > span');
  });

  test('element with class', () => {
    document.body.innerHTML = '<div><p class="intro">text</p></div>';
    const p = document.querySelector('p');
    expect(selectorPath(p)).toBe('div > p.intro');
  });

  test('nth-child disambiguation', () => {
    document.body.innerHTML = '<ul><li>first</li><li>second</li><li>third</li></ul>';
    const second = document.querySelectorAll('li')[1];
    expect(selectorPath(second)).toContain(':nth-child(2)');
  });

  test('stops at id', () => {
    document.body.innerHTML = '<div><section id="content"><p><span>deep</span></p></section></div>';
    const span = document.querySelector('span');
    const result = selectorPath(span);
    expect(result).toContain('section#content');
    expect(result).not.toContain('div >');
  });

  test('handles body child directly', () => {
    document.body.innerHTML = '<header>nav</header>';
    const header = document.querySelector('header');
    expect(selectorPath(header)).toBe('header');
  });
});

describe('textPreview', () => {
  test('returns direct text node content', () => {
    document.body.innerHTML = '<p>Hello world</p>';
    const p = document.querySelector('p');
    expect(textPreview(p)).toBe('Hello world');
  });

  test('truncates at 80 chars', () => {
    const longText = 'A'.repeat(100);
    document.body.innerHTML = `<p>${longText}</p>`;
    const p = document.querySelector('p');
    const result = textPreview(p);
    expect(result).toHaveLength(83); // 80 + '...'
    expect(result.endsWith('...')).toBe(true);
  });

  test('trims whitespace', () => {
    document.body.innerHTML = '<p>  spaced  </p>';
    const p = document.querySelector('p');
    expect(textPreview(p)).toBe('spaced');
  });

  test('falls back to textContent for nested elements', () => {
    document.body.innerHTML = '<div><span>nested</span></div>';
    const div = document.querySelector('div');
    expect(textPreview(div)).toBe('nested');
  });

  test('returns empty for empty element', () => {
    document.body.innerHTML = '<div></div>';
    const div = document.querySelector('div');
    expect(textPreview(div)).toBe('');
  });
});

describe('getDataAttrs', () => {
  test('collects data attributes', () => {
    document.body.innerHTML = '<div data-id="123" data-type="card">content</div>';
    const div = document.querySelector('div');
    expect(getDataAttrs(div)).toEqual({ id: '123', type: 'card' });
  });

  test('excludes data-inspector', () => {
    document.body.innerHTML = '<div data-inspector="panel" data-name="test">x</div>';
    const div = document.querySelector('div');
    expect(getDataAttrs(div)).toEqual({ name: 'test' });
  });

  test('excludes vannot-prefixed attrs', () => {
    document.body.innerHTML = '<div data-vannot-id="x" data-real="y">z</div>';
    const div = document.querySelector('div');
    expect(getDataAttrs(div)).toEqual({ real: 'y' });
  });

  test('returns empty object for no data attrs', () => {
    document.body.innerHTML = '<div class="plain">x</div>';
    const div = document.querySelector('div');
    expect(getDataAttrs(div)).toEqual({});
  });
});

describe('Export format', () => {
  test('feedback entry has all required fields', () => {
    const entry = {
      tag: 'button',
      id: 'submit-btn',
      classes: 'primary',
      textContent: 'Submit',
      dataAttrs: {},
      selector: 'form > button#submit-btn',
      rect: { x: 200, y: 400, w: 120, h: 40 },
      feedback: 'too small',
      timestamp: Date.now(),
      url: '/checkout',
    };

    expect(entry).toHaveProperty('tag');
    expect(entry).toHaveProperty('id');
    expect(entry).toHaveProperty('classes');
    expect(entry).toHaveProperty('textContent');
    expect(entry).toHaveProperty('dataAttrs');
    expect(entry).toHaveProperty('selector');
    expect(entry).toHaveProperty('rect');
    expect(entry).toHaveProperty('feedback');
    expect(entry).toHaveProperty('timestamp');
    expect(entry).toHaveProperty('url');
    expect(entry.rect).toHaveProperty('x');
    expect(entry.rect).toHaveProperty('y');
    expect(entry.rect).toHaveProperty('w');
    expect(entry.rect).toHaveProperty('h');
  });

  test('freehand entry includes drawing field', () => {
    const entry = {
      tag: '',
      id: '',
      classes: '',
      textContent: '',
      dataAttrs: {},
      selector: '',
      rect: { x: 50, y: 50, w: 100, h: 100 },
      feedback: 'circle this',
      timestamp: Date.now(),
      url: '/page',
      drawing: {
        strokes: [{ x: 50, y: 50 }, { x: 150, y: 150 }],
        recognized_shape: 'circle',
        shape_confidence: 0.85,
      },
    };

    expect(entry.drawing).not.toBeNull();
    expect(entry.drawing.recognized_shape).toBe('circle');
    expect(entry.drawing.strokes).toHaveLength(2);
  });

  test('feedback format compatibility — entries are array-wrappable', () => {
    const entries = [
      { tag: 'h1', id: '', classes: 'title', textContent: 'Hello', dataAttrs: {},
        selector: 'h1.title', rect: { x: 0, y: 0, w: 500, h: 40 },
        feedback: 'make bigger', timestamp: 123, url: '/' },
    ];
    const json = JSON.stringify(entries);
    const parsed = JSON.parse(json);
    expect(Array.isArray(parsed)).toBe(true);
    expect(parsed[0].feedback).toBe('make bigger');
  });
});

describe('Mode interaction', () => {
  // Replicate the mutual exclusivity logic from content.js setModes handler
  function enforceModes(modes) {
    var newModes = new Set(modes);
    if (newModes.has('draw') && newModes.has('inspect')) {
      newModes.delete('inspect');
    }
    return newModes;
  }

  // Replicate the popup.js toggleMode logic
  function toggleMode(activeModes, mode) {
    var result = new Set(activeModes);
    if (result.has(mode)) {
      result.delete(mode);
    } else {
      result.add(mode);
      if (mode === 'draw') result.delete('inspect');
      if (mode === 'inspect') result.delete('draw');
    }
    return result;
  }

  test('draw and inspect are mutually exclusive in setModes', () => {
    const result = enforceModes(['draw', 'inspect']);
    expect(result.has('draw')).toBe(true);
    expect(result.has('inspect')).toBe(false);
  });

  test('activating draw deactivates inspect in popup', () => {
    const modes = new Set(['inspect']);
    const result = toggleMode(modes, 'draw');
    expect(result.has('draw')).toBe(true);
    expect(result.has('inspect')).toBe(false);
  });

  test('activating inspect deactivates draw in popup', () => {
    const modes = new Set(['draw']);
    const result = toggleMode(modes, 'inspect');
    expect(result.has('inspect')).toBe(true);
    expect(result.has('draw')).toBe(false);
  });

  test('audio is independent of draw/inspect', () => {
    const modes = new Set(['inspect']);
    const result = toggleMode(modes, 'audio');
    expect(result.has('inspect')).toBe(true);
    expect(result.has('audio')).toBe(true);
  });

  test('screen is independent of draw/inspect', () => {
    const modes = new Set(['draw', 'audio']);
    const result = toggleMode(modes, 'screen');
    expect(result.has('draw')).toBe(true);
    expect(result.has('audio')).toBe(true);
    expect(result.has('screen')).toBe(true);
  });

  test('toggling active mode deactivates it', () => {
    const modes = new Set(['draw', 'audio']);
    const result = toggleMode(modes, 'draw');
    expect(result.has('draw')).toBe(false);
    expect(result.has('audio')).toBe(true);
  });

  test('setModes preserves audio and screen alongside draw', () => {
    const result = enforceModes(['draw', 'audio', 'screen']);
    expect(result.has('draw')).toBe(true);
    expect(result.has('audio')).toBe(true);
    expect(result.has('screen')).toBe(true);
  });
});
