// Copyright 2026 Amazon Inc

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// WARNING: this file is auto-generated by scripts/generate_sync.py
// Source: src/nova_act/asyncio/nova_act.py
// DO NOT EDIT — changes will be overwritten. Modify the async source instead.
import './App.css'

const episodes = [
  {
    number: 1,
    title: "What Even Is Intelligence? (Asking for a Friend's Neural Network)",
    quote: "If my toaster could pass a Turing test, would I still be allowed to unplug it?",
    guest: "Dr. Sarah Chen, Cognitive Systems Research",
    description: "In our debut episode, Dr. Thoughtsworth explores the surprisingly blurry line between 'genuinely intelligent' and 'really good at autocomplete.' We discuss why defining intelligence is harder than achieving it, and why philosophers are suddenly getting invited to engineering standups.",
    duration: "42 min",
  },
  {
    number: 2,
    title: "Emergent Behavior: When Your Model Does Things You Didn't Ask For",
    quote: "We trained it on Shakespeare and it started writing passive-aggressive Slack messages. That's emergence.",
    guest: "Prof. James Okafor, Emergent Computing Lab",
    description: "Prof. Gradient walks us through the delightful chaos of emergent behavior in large-scale models. From unexpected poetry to unsolicited career advice, we explore what happens when systems develop capabilities their creators never anticipated — and whether we should be impressed or concerned.",
    duration: "38 min",
  },
  {
    number: 3,
    title: "The Embodiment Problem: Giving AI a Body Without Making It Weird",
    quote: "The robot didn't fail the task. It simply chose to contemplate the task instead. Very philosophical.",
    guest: "Dr. Anita Patel, Robotics & Embodied Intelligence",
    description: "Can intelligence truly exist without a physical form? Dr. Actuator argues yes, but also admits her lab's robot spent three hours 'thinking about' picking up a cup before gently pushing it off the table. We discuss the gap between simulated understanding and physical competence.",
    duration: "45 min",
  },
  {
    number: 4,
    title: "Memory, Attention, and Why Your AI Forgot What You Said 30 Seconds Ago",
    quote: "Long-term memory in AI is like my memory at the grocery store — theoretically possible, rarely executed.",
    guest: "Dr. Marcus Liu, Memory & Attention Systems",
    description: "Dr. Liu explains why memory remains one of the hardest problems in AI. We cover everything from attention mechanisms to the existential dread of a context window that's just slightly too small for your prompt, and why 'just make it bigger' isn't always the answer.",
    duration: "36 min",
  },
  {
    number: 5,
    title: "Multi-Agent Systems: Teaching AIs to Cooperate (and Fail Spectacularly)",
    quote: "Agent 1 thought Agent 2 was handling it. Agent 2 thought Agent 1 was handling it. The server room is fine.",
    guest: "Dr. Elena Vasquez, Distributed AI Group",
    description: "What happens when you put multiple AI agents in a room and ask them to collaborate? Dr. Vasquez shares tales from the frontier of multi-agent systems, including the time two agents got into an infinite politeness loop and the server costs hit five figures before anyone noticed.",
    duration: "41 min",
  },
  {
    number: 6,
    title: "Reasoning vs. Pattern Matching: The Debate That Ended Three Friendships",
    quote: "It's not reasoning. It's just — okay, fine, maybe it's a little bit reasoning.",
    guest: "Prof. David Kim & Dr. Rachel Stein, Computational Epistemology",
    description: "Two researchers who famously disagree on whether large language models 'truly reason' sit down for a civil conversation. (The civility lasts approximately seven minutes.) We explore what reasoning means, why it matters, and why this question has divided more labs than any technical disagreement in recent memory.",
    duration: "52 min",
  },
  {
    number: 7,
    title: "Benchmarks: Measuring Intelligence Without Accidentally Measuring Vibes",
    quote: "We created a new benchmark. It was saturated in six weeks. We are tired.",
    guest: "Dr. Fatima Al-Hassan, AI Evaluation Research",
    description: "How do you measure something you can't define? Dr. Al-Hassan discusses the Sisyphean task of creating AI benchmarks that remain relevant for longer than a product cycle. From contaminated test sets to the philosophical implications of 'teaching to the test,' this episode is a love letter to everyone who's ever watched their carefully crafted evaluation become obsolete overnight.",
    duration: "39 min",
  },
  {
    number: 8,
    title: "The Alignment Tax: Making AI Nice Without Making It Boring",
    quote: "The model used to be creative and unhinged. Now it's helpful and writes like a corporate email. Progress?",
    guest: "Dr. Thomas Bergmann, AI Safety & Ethics",
    description: "Dr. Bergmann tackles the tension between making AI systems safe and making them useful. We discuss the alignment tax — the performance cost of being responsible — and whether there's a future where AI can be both reliably helpful and occasionally surprising in a good way.",
    duration: "44 min",
  },
]

function App() {
  return (
    <>
      <header className="header">
        <div className="header-inner">
          <div className="logo">
            <span className="logo-icon">🧠</span>
            Probably Sentient Labs
          </div>
          <nav>
            <ul className="nav-links">
              <li><a href="#">Blog</a></li>
              <li><a href="#">Careers</a></li>
              <li><a href="#" className="active">Podcast</a></li>
            </ul>
          </nav>
        </div>
      </header>

      <section className="hero">
        <div className="hero-content">
          <span className="hero-badge">NEW PODCAST</span>
          <h1>The Thinking Cap Podcast</h1>
          <p className="hero-subtitle">
            Where researchers discuss intelligence — artificial, biological, and occasionally accidental.
          </p>
        </div>
      </section>

      <main className="main-content">
        <div className="meta">
          <span className="meta-tag">Machine Learning</span>
          <span className="meta-tag">Cognitive Science</span>
          <span>Published July 11, 2026</span>
        </div>

        <div className="intro">
          <p>
            We're thrilled to announce <strong><em>The Thinking Cap Podcast</em></strong>, a new podcast
            from Probably Sentient Labs. Hosted by Dr. Mira Johansson, the show brings together
            researchers, engineers, and the occasional philosopher to explore the big questions about
            intelligence — what it is, how to build it, and whether it'll remember your name after
            a context window refresh. New episodes weekly, or whenever the inference costs clear.
          </p>
        </div>

        {episodes.map((ep) => (
          <article key={ep.number} className="episode">
            <div className="episode-header">
              <span className="episode-number">{ep.number}</span>
              <h2>{ep.title}</h2>
            </div>
            <blockquote className="episode-quote">"{ep.quote}"</blockquote>
            <p className="episode-guest">Featuring: {ep.guest}</p>
            <p>{ep.description}</p>
            <div className="episode-player">
              <button className="play-btn" aria-label={`Play episode ${ep.number}`}>▶</button>
              <div className="player-info">
                <div className="player-title">Episode {ep.number}: {ep.title}</div>
                <div className="player-duration">{ep.duration}</div>
              </div>
            </div>
          </article>
        ))}
      </main>

      <section className="streaming-section">
        <h3>Listen Wherever You Pretend to Pay Attention</h3>
        <div className="streaming-links">
          <a href="#" className="streaming-link">🎬 YouTube</a>
          <a href="#" className="streaming-link">🎵 Spotify</a>
          <a href="#" className="streaming-link">🍎 Apple Podcasts</a>
          <a href="#" className="streaming-link">🎧 Wherever Podcasts Exist</a>
        </div>
      </section>

      <footer className="footer">
        <div className="footer-inner">
          <p>© 2026 Probably Sentient Labs — A division of "We'll Figure It Out Eventually, Inc."</p>
          <p style={{ marginTop: '0.5rem' }}>
            <a href="#">Research</a> · <a href="#">Careers</a> · <a href="#">Ethics (We're Trying)</a>
          </p>
        </div>
      </footer>
    </>
  )
}

export default App
